<p style="color:#FFF; background:#07D; padding:12px; font-size:20px; font-style:italic; text-align:center">
<span style="width:49%; display:inline-block; text-align:left">Christophe Schlick</span>
<span style="width:49%; display:inline-block; text-align:right">schlick[at]u-bordeaux.fr</span>
<span style="font-size:48px; font-style:normal"><b>PACKAGE : PANDAS</b></span><br>
<span style="width:49%; display:inline-block; text-align:left">Version 2022-06</span>
<span style="width:49%; display:inline-block; text-align:right">Licence CC-BY-NC-ND</span></p>

Le package [**pandas**](http://pandas.pydata.org) (contraction de ***Panel Data Analysis***) fournit à Python des outils pour manipuler des tableaux de données de toute nature. Le package **pandas** est presque toujours utilisé en collaboration avec le package **numpy**, chacun d'eux fournissant des outils de traitement spécifiques. Plus précisément, il y a quatre différences fondamentales entre les fonctionnalités offertes par  **numpy** et celles offertes par **pandas** :

- Le package **numpy** fournit un seul type de conteneur (appelé **`array`**) qui peut avoir un nombre quelconque de dimensions, alors que le package **pandas** fournit trois types de conteneurs : un conteneur 1D (appelé **`series`**), un conteneur 2D (appelé **`dataframe`**) et un conteneur 3D (appelé **`panel`**). Il n'y a pas de traduction française "officielle" pour le nom des conteneurs fournis par **pandas**. Dans ce cours, nous allons utiliser les termes **série** pour **`series`**, **table** pour **`dataframe`** et **classeur** pour **`panel`**.
- une matrice **numpy** doit avoir toutes ses données du même type, ce qui est également le cas pour les séries **pandas**. Par contre, une table ou un classeur **pandas** peut contenir un nombre quelconque de type de données (habituellement on va avoir un type de données par série) 
- les dimensions d'une matrice **numpy** sont toujours indexées par des entiers démarrant à 0, alors que chaque dimension des conteneurs **pandas** possède un index de nature arbitraire pour identifier ses éléments (on peut considérer un index comme un équivalent des clés d'un dictionnaire) 
- même si les matrices **numpy** peuvent contenir des cases vides (identifiées par la valeur **`NaN`**), celles-ci vont empêcher l'utilisation d'un grand nombre d'outils **numpy** qui nécessitent des matrices à données complètes. A l'inverse, **pandas** sait gérer beaucoup mieux les données partielles, et propose plusieurs outils pour traiter automatiquement les données manquantes, ce qui le rend beaucoup souple pour le traitement des données ***dans la vraie vie***, où les bases de données sans trous ou sans données aberrantes sont extrêmement rares.

La manière la plus intuitive pour comprendre les conteneurs fournis par **pandas** est de se référer à l'***organisation des données dans un tableur***, tel que *Microsoft Excel, Google Sheets, LibreOffice Calc* ou autre : l'ensemble des données stockées dans le classeur complet manipulé par le tableur correspond au type **`panel`** , les données stockées dans un onglet spécifique du classeur correspond au type **`dataframe`** , et enfin, les données stockées dans une colonne d'un des onglets correspond au type **`series`**.

La documentation complète du package se trouve sur le site [**pandas.org**](https://pandas.pydata.org/docs/user_guide), mais elle est également directement disponible dans le menu `Help` de l'interface Jupyter. Ce notebook a pour objet de faire un tour d'horizon rapide et de montrer les fonctionnalités les plus utiles de **matplotlib** dans le cadre d'une utilisation au sein de l'environnement Jupyter.

> **Remarque importante :**  Dans les versions récentes de **pandas**, le conteneur 3D **`panel`** (qui était pourtant à la base du nom du package) a été supprimé car il n'apportait pas beaucoup plus de fonctionnalités qu'un simple dictionnaire Python regroupant une série de conteneurs 2D **`dataframe`**. La suppression de ce conteneur 3D a été motivée par l'inclusion dans **pandas** d'un mécanisme d'indexation très puissant, appelé **`MultiIndex`**, permettant de créer des structures hiérarchiques de dimensions arbitraires. Etant donnée sa complexité, la mise en oeuvre des **`MultiIndex`** ne sera pas détaillée dans ce cours, qui se contentera de regrouper des tables en utilisant un dictionnaire Python ou un vecteur **numpy** lorsqu'une troisième dimension sera nécessaire.
---
On importe habituellement le package **pandas** par le biais d'un alias court, avec la commande suivante :
> `import pandas as pd`

In [26]:
import numpy as np # import du package 'numpy' avec alias 'np' 
import pandas as pd # import du package 'pandas' avec alias 'pd'
from SRC.tools import show # import de la fonction 'show' permettant de simplifier certaines explications
from IPython.core.interactiveshell import InteractiveShell as ish
ish.ast_node_interactivity = "all" # 'last_expr' pour revenir au mode par défaut
ish.ast_node_interactivity = "last_expr" # 'last_expr' pour revenir au mode par défaut

<h2 style="padding:16px; color:#FFF; background:#07D">A - Création et accès aux séries et aux tables</h2>

### 1 - Création de séries

Dans la terminologie de **pandas**, une série (***series***) est un conteneur ordonné 1D dont l'accès aux éléments peut s'effectuer soit par leur position (comme c'est le cas pour les listes en Python) soit par un index spécifique associé à ces éléments (comme c'est le cas pour les dictionnaires en Python). Néanmoins, à la différence des listes et des dictionnaires standards, tous les éléments d'une série doivent être de même nature, comme c'est le cas pour les matrices **numpy**.

In [422]:
vec = [0, 50, 150, 300, 500] # création d'un vecteur de test (liste 1D standard)
show("vec")

vec = [0, 50, 150, 300, 500]

In [423]:
a = pd.Series(vec) # création d'une série à partir du vecteur de test
show("a#;; a.values; a.index; a.index.values") # par défaut, les séries ont un index de type 'RangeIndex'

a =
0      0
1     50
2    150
3    300
4    500
dtype: int64

a.values = [  0  50 150 300 500]
a.index = RangeIndex(start=0, stop=5, step=1)
a.index.values = [0 1 2 3 4]

Avec l'index de type **`RangeIndex`** créé par défaut, une série se comporte globalement comme un vecteur **numpy** : on peut accéder à ses éléments soit par indice, soit par tranche, soit par énumération, soit par prédicat.

In [424]:
show("a[1];") # accès par indice
show("a[1:4]#;") # accès par tranche d'indices
show("a[[4,2,1]]#;") # accès par énumeration (ATTENTION : il faut une liste pas un tuple)
show("a[a > 200]#") # accès par prédicat

a[1] = 50

a[1:4] =
1     50
2    150
3    300
dtype: int64

a[[4,2,1]] =
4    500
2    150
1     50
dtype: int64

a[a > 200] =
3    300
4    500
dtype: int64

---
On peut modifier le comportement d'une série, on choisissant un autre type d'index :

In [425]:
b = pd.Series(vec, index=[4,2,5,1,8]) # on définit manuellement un index composé d'entiers non ordonnés
#b = pd.Series(dict(zip([4,2,5,1,8], vec))) # solution alternative à base de dictionnaire
show("b#;; b.values; b.index; b.index.values")

b =
4      0
2     50
5    150
1    300
8    500
dtype: int64

b.values = [  0  50 150 300 500]
b.index = Int64Index([4, 2, 5, 1, 8], dtype='int64')
b.index.values = [4 2 5 1 8]

> **ATTENTION :** l'utilisation d'index de type **`IntIndex`** nécessite une ***attention particulière*** car cela implique une utilisation parfois contre-intuitive qui peut être source de nombreuses erreurs. Comme on
peut le constater ci-dessous, **`b[n]`** utilise les valeurs de l'index, mais **`b[m:n]`** utilise les valeurs des positions :

In [426]:
show("b[1];") # accès par indice (ATTENTION : on utilise les valeurs de l'index)
show("b[1:4]#;") # accès par tranche (ATTENTION : on utilise les valeurs des positions)
show("b[[4,2,1]]#;") # accès par énumération (on utilise à nouveau les valeurs de l'index)
show("b[b > 200]#") # accès par prédicat

b[1] = 300

b[1:4] =
2     50
5    150
1    300
dtype: int64

b[[4,2,1]] =
4      0
2     50
1    300
dtype: int64

b[b > 200] =
1    300
8    500
dtype: int64

---
Une bien meilleure option est d'utiliser un index à base de chaînes de caractères, appelés ***labels*** :

In [7]:
c = pd.Series(vec, index=['A','B','C','D','E']) # on définit un index composé de labels
#c = pd.Series(dict(zip('ABCDE', vec))) # solution alternative à base de dictionnaire
show("c#;; c.values; c.index; c.index.values")

c =
A      0
B     50
C    150
D    300
E    500
dtype: int64

c.values = [  0  50 150 300 500]
c.index = Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
c.index.values = ['A' 'B' 'C' 'D' 'E']

Avec un index à base de labels, le comportement devient très souple et très intuitif :
- on peut utiliser des indices ou des tranches, aussi bien sur les positions que sur les labels
- on peut même utiliser la notation pointée pour accéder à un élément d'une série via son label

In [8]:
show("c[1];") # accès par position
show("c['D'];") # accès par label
show("c.D;") # accès par attribut (via la notation pointée)
show("c[1:4]#;") # accès par tranche de positions
show("c['B':'D']#;") # accès par tranche de labels (ATTENTION : 2 bornes incluses)
show("c[[4,2,1]]#;") # accès par énumération de positions
show("c[['E','C','B']]#;") # accès par énumération de labels
show("c[c > 200]#") # accès par prédicat

c[1] = 50

c['D'] = 300

c.D = 300

c[1:4] =
B     50
C    150
D    300
dtype: int64

c['B':'D'] =
B     50
C    150
D    300
dtype: int64

c[[4,2,1]] =
E    500
C    150
B     50
dtype: int64

c[['E','C','B']] =
E    500
C    150
B     50
dtype: int64

c[c > 200] =
D    300
E    500
dtype: int64

> **Note :** contrairement aux tranches de positions, une tranche de labels ***inclut les deux bornes de l'intervalle***

> **Note :** la notation pointée ne fonctionne que si les labels n'utilisent que les 63 caractères autorisés
pour un identificateur Python : `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_`
---
Aussi bien les données que les index d'une série **pandas** peuvent également être définis à partir de vecteurs **numpy** :

In [9]:
d = pd.Series(np.random.randint(0, 1000, 11)) # utilisation de l'index par défaut
show("d#;; d.values; d.index.values")

d =
0     339
1     240
2     918
3     467
4     556
5     159
6      47
7     217
8     411
9     223
10    775
dtype: int32

d.values = [339 240 918 467 556 159  47 217 411 223 775]
d.index.values = [ 0  1  2  3  4  5  6  7  8  9 10]

In [10]:
d.index = np.linspace(0,1,11) # on peut modifier l'index d'une série à tout moment
show("d#;; d.values; d.index; d.index.values")

d =
0.0    339
0.1    240
0.2    918
0.3    467
0.4    556
0.5    159
0.6     47
0.7    217
0.8    411
0.9    223
1.0    775
dtype: int32

d.values = [339 240 918 467 556 159  47 217 411 223 775]
d.index = Float64Index([                0.0,                 0.1,                 0.2,
              0.30000000000000004,                 0.4,                 0.5,
               0.6000000000000001,  0.7000000000000001,                 0.8,
                              0.9,                 1.0],
             dtype='float64')
d.index.values = [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

> **ATTENTION :** l'utilisation d'index de type **`FloatIndex`** est ***fortement déconseillée*** car les erreurs d'arrondis entre stockage binaire et affichage décimal, vont empêcher l'accès à certaines données.
On peut voir ci-dessous que l'indice 0.3 n'existe pas car il est stocké comme 0.30000000000000004 :

In [11]:
show("d[0.1];") # la valeur 0.1 existe dans l'index
show("d[0.35:0.85]#;") # on peut utiliser des valeurs intermédiaires pour les tranches
#show("d[0.3]") # la valeur 0.3 n'existe pas dans l'index (enlever le commentaire pour générer l'erreur)
show("0.3 in d.index; 0.30000000000000004 in d.index") # origine du problème

d[0.1] = 240

d[0.35:0.85] =
0.4    556
0.5    159
0.6     47
0.7    217
0.8    411
dtype: int32

0.3 in d.index = False
0.30000000000000004 in d.index = True

---
Pour manipuler des valeurs réelles dans un index, il est préférable de créer un **`IntervalIndex`**
qui permet d'associer un intervalle de valeurs à chaque indice, plutôt qu'une valeur unique. Cela s'avère particulièrement utile lorsque l'on doit réaliser un partitionnement ou un regroupement de données :

In [12]:
intervals = pd.interval_range(0, 10, freq=2.5, closed='left') # closed : left|right|both|neither
#intervals = pd.interval_range(0, 100, 5, closed='both')
e = pd.Series(np.random.rand(intervals.size), index=intervals)
show("e#;; e.values; e.index")

e =
[0.0, 2.5)     0.400588
[2.5, 5.0)     0.900735
[5.0, 7.5)     0.959771
[7.5, 10.0)    0.255538
dtype: float64

e.values = [0.40058798 0.90073487 0.95977111 0.25553783]
e.index = IntervalIndex([[0.0, 2.5), [2.5, 5.0), [5.0, 7.5), [7.5, 10.0)], dtype='interval[float64, left]')

In [13]:
show("e[2.4999999]; e[2.5]; e[2.5000001];") # l'intervalle est respecté selon la valeurs de l'indice
show("e[1:3]#;") # une tranche d'entiers utilise les positions
show("e[3.0:5.5]#") # une tranche de réels utilise les intervalles

e[2.4999999] = 0.40058797584850736
e[2.5] = 0.9007348656308191
e[2.5000001] = 0.9007348656308191

e[1:3] =
[2.5, 5.0)    0.900735
[5.0, 7.5)    0.959771
dtype: float64

e[3.0:5.5] =
[2.5, 5.0)    0.900735
[5.0, 7.5)    0.959771
dtype: float64

---
Dans le même ordre d'idée, les types **`DatetimeIndex`** et **`TimedeltaIndex`** permettent de créer des index spécifiques pour les séries temporelles, qui seront définis par une date/heure de début, un nombre de périodes, et une fréquence pour la génération des valeurs temporelles. Il est possible d'utiliser les symboles suivants pour définir la fréquence :

**`N`** = nanoseconde, **`U`** = microseconde, **`L`** = milliseconde, **`S`** = seconde, **`T`** = minute,
**`H`** = heure,

**`D`** = jour, **`W`** ou **`W-day`** = semaine, **`M`** ou **`MS`** = mois, **`Q`** ou **`QS`** = trimestre, **`Y`** ou **`YS`** = année

> **Note :** Les dates générées pour **M**, **Q** et **Y** correspondent au dernier jour de la période concernée, alors que les dates pour **MS**, **QS** et **YS** correspondent au premier jour (le suffixe **S** signifie ***start***). De même, les dates générées par **W** correspondent au dimanche (dernier jour de la semaine) mais on peut choisir le jour en utilisant **W-*day*** avec ***day*** pouvant prendre les valeurs suivantes : **`MON/TUE/WED/THU/FRI/SAT/SUN`**

In [429]:
index = pd.date_range('2000-01-01', periods=6, freq='MS') # création d'un index avec fréquence mensuelle
#index = pd.date_range('now', periods=6, freq='W-MON').round('D') # idem avec fréquence hebdomadaire (samedi)
#index = pd.timedelta_range('0S', periods=7, freq='5S').round('S') # idem avec un intervalle de 5 secondes
#index = pd.timedelta_range('15H', periods=9, freq='1H30T').round('T') # idem avec un intervalle de 1H30
f = pd.Series(np.random.rand(index.size), index=index)
show("f#;; f.values#;; f.index#")

f =
2000-01-01    0.368242
2000-02-01    0.957155
2000-03-01    0.140351
2000-04-01    0.870087
2000-05-01    0.473608
2000-06-01    0.800911
Freq: MS, dtype: float64

f.values =
[0.36824154 0.95715516 0.14035078 0.87008726 0.47360805 0.80091075]

f.index =
DatetimeIndex(['2000-01-01', '2000-02-01', '2000-03-01', '2000-04-01',
               '2000-05-01', '2000-06-01'],
              dtype='datetime64[ns]', freq='MS')

In [15]:
show("f[1];") # un indice entier utilise les positions
show("f[1:4]#;") # idem pour les tranches d'entiers
show("f['2000-02-01']#;") # un indice chaîne de caractères utilise les dates
show("f['2000-02':'2000-04']#") # idem pour les tranches de chaînes

f[1] = 0.3583508806059855

f[1:4] =
2000-02-01    0.358351
2000-03-01    0.054714
2000-04-01    0.160987
Freq: MS, dtype: float64

f['2000-02-01'] =
0.3583508806059855

f['2000-02':'2000-04'] =
2000-02-01    0.358351
2000-03-01    0.054714
2000-04-01    0.160987
Freq: MS, dtype: float64

---
### 2 - Création de tables

Dans la terminologie de **pandas**, une table (***dataframe***) est un conteneur 2D qui est obtenu en agglomérant un ensemble de séries possédant toutes le même index. La convention usuelle est de considérer que chaque série représente une colonne de la table résultante (même si on peut évidemment appliquer l'opérateur de transposition si la configuration inverse est préférable pour un jeu de données particulier)

In [16]:
mat = [[1,-2,3,-4], [-5,6,-7,8], [9,-10,11,-12]] # création d'une matrice de test (liste 2D standard)
show("mat")

mat = [[1, -2, 3, -4], [-5, 6, -7, 8], [9, -10, 11, -12]]

In [17]:
aa = pd.DataFrame(mat) # création d'une table à partir de la matrice de test
aa # la table pandas est affichée dans le notebook sous la forme d'une table HTML

   0   1   2   3
0  1  -2   3  -4
1 -5   6  -7   8
2  9 -10  11 -12

In [18]:
# les données d'une table 'pandas' sont stockées dans l'attribut 'values' qui est une matrice 'numpy'
show("aa#;; aa.ndim; aa.shape; aa.size;; aa.values#; aa.values.nbytes; aa.values.dtype")

aa =
   0   1   2   3
0  1  -2   3  -4
1 -5   6  -7   8
2  9 -10  11 -12

aa.ndim = 2
aa.shape = (3, 4)
aa.size = 12

aa.values =
[[  1  -2   3  -4]
 [ -5   6  -7   8]
 [  9 -10  11 -12]]
aa.values.nbytes = 96
aa.values.dtype = int64

In [19]:
# par défaut, les lignes et les colonnes d'une table 'pandas' ont un index de type 'RangeIndex'
show("aa.index; aa.index.values; aa.columns; aa.columns.values")

aa.index = RangeIndex(start=0, stop=3, step=1)
aa.index.values = [0 1 2]
aa.columns = RangeIndex(start=0, stop=4, step=1)
aa.columns.values = [0 1 2 3]

---
Une des caractéristiques particulières du système d'indexation utilisé par les tables **pandas** est qu'il est assymétrique : les ***indices s'appliquent aux colonnes***, les ***tranches d'indices s'appliquent aux lignes***. C'est un peu déroutant au départ, mais à l'usage, il s'avère que ce choix est judicieux par rapport aux manipulations habituellement effectuées sur une telle table. Si l'on souhaite accéder à une ligne unique ou à une tranche de colonnes, la manière la plus simple est d'appliquer une transposition à la table, ou alors utiliser les attributs **`.loc`** et **`.iloc`** créés pour cet usage :

In [22]:
show("aa[1]#;") # accès à une colonne 
show("aa.T[1]#;") # accès à une ligne
show("aa.iloc[1]#;") # idem avec 'iloc' : aa.T[1] <=> aa.iloc[1]
show("aa[1:3]#;") # accès à une tranche de lignes
show("aa.T[1:3].T#;") # accès à une tranche de colonnes
show("aa.iloc[:,1:3]#") # idem avec 'iloc': aa.T[1:3].T <=> aa.iloc[:,1:3]

aa[1] =
0    -2
1     6
2   -10
Name: 1, dtype: int64

aa.T[1] =
0   -5
1    6
2   -7
3    8
Name: 1, dtype: int64

aa.iloc[1] =
0   -5
1    6
2   -7
3    8
Name: 1, dtype: int64

aa[1:3] =
   0   1   2   3
1 -5   6  -7   8
2  9 -10  11 -12

aa.T[1:3].T =
    1   2
0  -2   3
1   6  -7
2 -10  11

aa.iloc[:,1:3] =
    1   2
0  -2   3
1   6  -7
2 -10  11

---
Comme pour les matrices **numpy**, on peut utiliser l'accès par énumération ou par prédicat pour les tables **pandas**, avec néanmoins deux différences notables :

- L'énumération doit nécessairement utiliser une liste d'indices (et non un tuple)
- Les données de la table qui ne vérifient pas le prédicat ne sont pas supprimées dans les valeurs retournées, mais sont remplacées par **`NaN`** (***Not-A-Number***)

In [23]:
show("aa[[3,1]]#;") # accès par énumération de colonnes
show("aa.iloc[[2,0]]#;") # accès par énumération de lignes
show("aa[aa % 5 != 0]#") # accès par prédicat

aa[[3,1]] =
    3   1
0  -4  -2
1   8   6
2 -12 -10

aa.iloc[[2,0]] =
   0   1   2   3
2  9 -10  11 -12
0  1  -2   3  -4

aa[aa % 5 != 0] =
     0    1   2   3
0  1.0 -2.0   3  -4
1  NaN  6.0  -7   8
2  9.0  NaN  11 -12

> **Remarque importante :** Chaque fois qu'une opération fait apparaître un élément **`NaN`** dans une série, tous les éléments de cette série sont convertis en **`float`**, car la valeur **`NaN`** fait partie de l'encodage des réels, selon la norme IEEE 754. Lorsqu'un **`NaN`** apparait dans une table, seules les colonnes concernées sont converties en **`float`**. On peut le constater dans la table ci-dessus : les colonnes 0 et 1 contiennent un **`NaN`** et sont donc converties en **`float`**, alors que les colonnes 2 et 3
restent de type **`int`**
---
Il est très rare de garder l'index numérique par défaut pour les colonnes d'une table **pandas**. En effet, comme ces colonnes correspondent presque toujours à des séries, on va généralement attribuer un ***label*** à chaque colonne pour indiquer la nature des valeurs qui s'y trouvent, comme on le fait classiquement dans un tableur :

In [436]:
bb = pd.DataFrame(mat, columns=list('ABCD'))
bb

   A   B   C   D
0  1  -2   3  -4
1 -5   6  -7   8
2  9 -10  11 -12

In [439]:
# le type de données utilisé pour les labels est le type 'object'
show("bb#;; bb.values#; bb.index; bb.index.values; bb.columns; bb.columns.values")

bb =
   A   B   C   D
0  1  -2   3  -4
1 -5   6  -7   8
2  9 -10  11 -12

bb.values =
[[  1  -2   3  -4]
 [ -5   6  -7   8]
 [  9 -10  11 -12]]
bb.index = RangeIndex(start=0, stop=3, step=1)
bb.index.values = [0 1 2]
bb.columns = Index(['A', 'B', 'C', 'D'], dtype='object')
bb.columns.values = ['A' 'B' 'C' 'D']

Avec des index de types différents, l'assymétrie des lignes et des colonnes semble plus naturelle. Et à nouveau, on bénéficie d'un accès par attribut, utilisant la notation pointée pour accéder à une colonne directement par son label (d'où l'intérêt d'***utiliser des labels qui ne contiennent que les 63 caractères autorisés pour les identificateurs*** en Python) :

In [440]:
show("bb['B']#;") # accès à une colonne par label
show("bb.B#;") # idem à une colonne par attribut (via la notation pointée)
show("bb.T[1]#;") # accès à une ligne par position <=> bb.iloc[1]
show("bb[1:3]#;") # accès à une tranche de ligne par positions
show("bb.T['B':'D'].T#") # accès à une tranche de colonne par labels <=> bb.loc[:,'B':'D']

bb['B'] =
0    -2
1     6
2   -10
Name: B, dtype: int64

bb.B =
0    -2
1     6
2   -10
Name: B, dtype: int64

bb.T[1] =
A   -5
B    6
C   -7
D    8
Name: 1, dtype: int64

bb[1:3] =
   A   B   C   D
1 -5   6  -7   8
2  9 -10  11 -12

bb.T['B':'D'].T =
    B   C   D
0  -2   3  -4
1   6  -7   8
2 -10  11 -12

---
Utiliser des labels pour les colonnes et des numéros pour les lignes est de très loin l'utilisation la plus classique des tables **pandas** : comme les séries mises en colonnes dans une table doivent toutes partager le même index, choisir un index de type **`RangeIndex`** consistant à numéroter les lignes, est effectivement un moyen simple pour identifier sans ambiguité les éléments de chaque série. Néanmoins, il est parfois judicieux d'utiliser un index plus élaboré pour les lignes de la table : en particulier, les index de type **`IntervalIndex`** ou **`DatetimeIndex`** sont utiles dans de nombreuses situations concrètes :

In [441]:
dates, labels = pd.date_range('2000-01-01', periods=6, freq='MS'), list('ABCDEF')
data = np.random.normal(0, 5, (6,6)) + [range(10, 120, 20)]
cc = pd.DataFrame(data, index=dates, columns=labels)
cc

                    A          B          C          D          E           F
2000-01-01  17.547225  35.338876  46.567053  70.074367  88.121671  109.808882
2000-02-01  11.839872  29.776381  48.488124  58.877982  93.620032  111.795014
2000-03-01  15.380605  30.960704  54.264630  70.091786  92.141518  114.981389
2000-04-01   7.544252  33.563391  55.566702  59.231627  87.919443  104.645515
2000-05-01  11.105694  24.384714  44.746210  75.060395  97.718582  107.989426
2000-06-01  14.323746  28.865654  54.055801  71.438973  87.307659  119.542311

In [442]:
# L'accès aux colonnes (label ou tranche de labels) est inchangé par rapport à la table précédente
show("cc['B']#;") # accès à une colonne par label
show("cc.B#;") # accès à une colonne par attribut
show("cc.T['B':'E'].T#") # accès à une tranche de colonnes

cc['B'] =
2000-01-01    35.338876
2000-02-01    29.776381
2000-03-01    30.960704
2000-04-01    33.563391
2000-05-01    24.384714
2000-06-01    28.865654
Freq: MS, Name: B, dtype: float64

cc.B =
2000-01-01    35.338876
2000-02-01    29.776381
2000-03-01    30.960704
2000-04-01    33.563391
2000-05-01    24.384714
2000-06-01    28.865654
Freq: MS, Name: B, dtype: float64

cc.T['B':'E'].T =
                    B          C          D          E
2000-01-01  35.338876  46.567053  70.074367  88.121671
2000-02-01  29.776381  48.488124  58.877982  93.620032
2000-03-01  30.960704  54.264630  70.091786  92.141518
2000-04-01  33.563391  55.566702  59.231627  87.919443
2000-05-01  24.384714  44.746210  75.060395  97.718582
2000-06-01  28.865654  54.055801  71.438973  87.307659

In [443]:
# par contre, on dispose d'une plus grande variété pour l'accès aux lignes
show("cc.T['2000-03-01']#;") # accès à une ligne par date <=> cc.loc['2000-03-01']
show("cc.iloc[2]#;") # accès à une ligne par position
show("cc['20000301':'20000501']#;") # accès à une tranche de lignes par dates
show("cc[2:5]#;") # accès à une tranche de lignes par positions

cc.T['2000-03-01'] =
A     15.380605
B     30.960704
C     54.264630
D     70.091786
E     92.141518
F    114.981389
Name: 2000-03-01 00:00:00, dtype: float64

cc.iloc[2] =
A     15.380605
B     30.960704
C     54.264630
D     70.091786
E     92.141518
F    114.981389
Name: 2000-03-01 00:00:00, dtype: float64

cc['20000301':'20000501'] =
                    A          B          C          D          E           F
2000-03-01  15.380605  30.960704  54.264630  70.091786  92.141518  114.981389
2000-04-01   7.544252  33.563391  55.566702  59.231627  87.919443  104.645515
2000-05-01  11.105694  24.384714  44.746210  75.060395  97.718582  107.989426

cc[2:5] =
                    A          B          C          D          E           F
2000-03-01  15.380605  30.960704  54.264630  70.091786  92.141518  114.981389
2000-04-01   7.544252  33.563391  55.566702  59.231627  87.919443  104.645515
2000-05-01  11.105694  24.384714  44.746210  75.060395  97.718582  107.989426

---

Toutes les tables définies ci-dessus possèdent le même type de données pour chacune des cellules, ce qui les rend assez proches des matrices fournies par **numpy**. La fonctionnalité la plus intéressante des tables fournies par le package **pandas** est, au contraire, de pouvoir mixer des données de nature arbitraire, en utilisant une série différente pour chaque colonne. La manière la plus habituelle utilisée pour créer une variable de type **`dataframe`** est de fournir un dictionnaire Python, regroupant plusieurs séries, chacune étant associé avec un label de type chaîne :

In [444]:
dd = pd.DataFrame(dict(Name=[3*c for c in 'ABCDEF'], Model=pd.Categorical(2*['S','M','L']), Start=0,
     Stop=np.random.randint(0,100,(6,), dtype='u1'), Score=np.linspace(0, 3, 6), Test=dates.month > 3, 
     Date=dates, Delta=(pd.Timestamp('now') - dates).round('D')))
dd

  Name Model  Start  Stop  Score   Test       Date     Delta
0  AAA     S      0    67    0.0  False 2000-01-01 8366 days
1  BBB     M      0    31    0.6  False 2000-02-01 8335 days
2  CCC     L      0     3    1.2  False 2000-03-01 8306 days
3  DDD     S      0    18    1.8   True 2000-04-01 8275 days
4  EEE     M      0    17    2.4   True 2000-05-01 8245 days
5  FFF     L      0    51    3.0   True 2000-06-01 8214 days

In [445]:
# l'index des lignes est un 'RangeIndex' par défaut, celui des colonnes est un 'Index' de labels
show("dd.index; dd.index.values; dd.columns; dd.columns.values")

dd.index = RangeIndex(start=0, stop=6, step=1)
dd.index.values = [0 1 2 3 4 5]
dd.columns = Index(['Name', 'Model', 'Start', 'Stop', 'Score', 'Test', 'Date', 'Delta'], dtype='object')
dd.columns.values = ['Name' 'Model' 'Start' 'Stop' 'Score' 'Test' 'Date' 'Delta']

In [446]:
# l'attribut 'dtypes' est une série 'pandas' contenant le type de données utilisé pour chaque colonne
show("dd.dtypes#")

dd.dtypes =
Name              object
Model           category
Start              int64
Stop               uint8
Score            float64
Test                bool
Date      datetime64[ns]
Delta    timedelta64[ns]
dtype: object

In [447]:
# n'importe quelle colonne peut être utilisée comme index pour les lignes (attention aux doublons !)
dd.index = dd.Date # on utilise la colonne 'Date' comme index
dd.index = dd.Name # on utilise la colonne 'Name' comme index
#dd.index = dd.Test # la colonne 'Test' est un mauvais choix à cause des doublons
dd.index.name = None # le label de l'index est inutile, donc on le supprime
dd # la colonne utilisée comme index n'est pas enlevée de la table

    Name Model  Start  Stop  Score   Test       Date     Delta
AAA  AAA     S      0    67    0.0  False 2000-01-01 8366 days
BBB  BBB     M      0    31    0.6  False 2000-02-01 8335 days
CCC  CCC     L      0     3    1.2  False 2000-03-01 8306 days
DDD  DDD     S      0    18    1.8   True 2000-04-01 8275 days
EEE  EEE     M      0    17    2.4   True 2000-05-01 8245 days
FFF  FFF     L      0    51    3.0   True 2000-06-01 8214 days

<h2 style="padding:16px; color:#FFF; background:#07D">B - Manipulation des séries et des tables</h2>

Les séries et les tables **pandas** sont construites en se basant sur les vecteurs et matrices fournies par **numpy** (comme on l'a vu, les valeurs correspondantes sont stockées dans l'attribut **`values`** qui est de type **`array`**). Par conséquent, toutes les opérations et fonctions de **numpy** sont directement utilisables avec **pandas**. Mais le package offre d'autres fonctionnalités particulièrement intéressantes dans le cadre des applications en Science des Données, dont on va faire un tour d'horizon rapide dans cette section.

---
Lorsqu'on liste les fonctions globales fournies par le package **pandas**, on constate qu'il est nettement moins volumineux que **numpy** : ***120 fonction pour pandas contre 580 pour numpy***

In [448]:
print(' ● '.join(f for f in dir(pd) if f[0] != '_' and f.islower())) # liste des fonctions du package 'pandas'

api ● array ● arrays ● bdate_range ● compat ● concat ● core ● crosstab ● cut ● date_range ● describe_option ● errors ● eval ● factorize ● get_dummies ● get_option ● infer_freq ● interval_range ● io ● isna ● isnull ● json_normalize ● lreshape ● melt ● merge ● merge_asof ● merge_ordered ● notna ● notnull ● offsets ● option_context ● options ● pandas ● period_range ● pivot ● pivot_table ● plotting ● qcut ● read_clipboard ● read_csv ● read_excel ● read_feather ● read_fwf ● read_gbq ● read_hdf ● read_html ● read_json ● read_orc ● read_parquet ● read_pickle ● read_sas ● read_spss ● read_sql ● read_sql_query ● read_sql_table ● read_stata ● read_table ● read_xml ● reset_option ● set_eng_float_format ● set_option ● show_versions ● test ● testing ● timedelta_range ● to_datetime ● to_numeric ● to_pickle ● to_timedelta ● tseries ● unique ● util ● value_counts ● wide_to_long

A l'inverse, en listant les méthodes disponibles pour la manipulation des séries ou tables **pandas**, on constate qu'elles sont bien plus nombreuses que celles qui existent pour les matrices **numpy** : ***207 méthodes pour pandas contre 70 pour numpy***.

In [449]:
print(' ● '.join(f for f in dir(dd) if f[0] != '_' and f.islower())) # liste des fonctions du package 'numpy'

abs ● add ● add_prefix ● add_suffix ● agg ● aggregate ● align ● all ● any ● append ● apply ● applymap ● asfreq ● asof ● assign ● astype ● at ● at_time ● attrs ● axes ● backfill ● between_time ● bfill ● bool ● boxplot ● clip ● columns ● combine ● combine_first ● compare ● convert_dtypes ● copy ● corr ● corrwith ● count ● cov ● cummax ● cummin ● cumprod ● cumsum ● describe ● diff ● div ● divide ● dot ● drop ● drop_duplicates ● droplevel ● dropna ● dtypes ● duplicated ● empty ● eq ● equals ● eval ● ewm ● expanding ● explode ● ffill ● fillna ● filter ● first ● first_valid_index ● flags ● floordiv ● from_dict ● from_records ● ge ● get ● groupby ● gt ● head ● hist ● iat ● idxmax ● idxmin ● iloc ● index ● infer_objects ● info ● insert ● interpolate ● isin ● isna ● isnull ● items ● iteritems ● iterrows ● itertuples ● join ● keys ● kurt ● kurtosis ● last ● last_valid_index ● le ● loc ● lookup ● lt ● mad ● mask ● max ● mean ● median ● melt ● memory_usage ● merge ● min ● mod ● mode ● mul ● multiply ● ndim ● ne ● nlargest ● notna ● notnull ● nsmallest ● nunique ● pad ● pct_change ● pipe ● pivot ● pivot_table ● plot ● pop ● pow ● prod ● product ● quantile ● query ● radd ● rank ● rdiv ● reindex ● reindex_like ● rename ● rename_axis ● reorder_levels ● replace ● resample ● reset_index ● rfloordiv ● rmod ● rmul ● rolling ● round ● rpow ● rsub ● rtruediv ● sample ● select_dtypes ● sem ● set_axis ● set_flags ● set_index ● shape ● shift ● size ● skew ● slice_shift ● sort_index ● sort_values ● squeeze ● stack ● std ● style ● sub ● subtract ● sum ● swapaxes ● swaplevel ● tail ● take ● to_clipboard ● to_csv ● to_dict ● to_excel ● to_feather ● to_gbq ● to_hdf ● to_html ● to_json ● to_latex ● to_markdown ● to_numpy ● to_parquet ● to_period ● to_pickle ● to_records ● to_sql ● to_stata ● to_string ● to_timestamp ● to_xarray ● to_xml ● transform ● transpose ● truediv ● truncate ● tz_convert ● tz_localize ● unstack ● update ● value_counts ● values ● var ● where ● xs

 Cela est due à une différence fondamentale d'architecture entre les deux bibliothèques : **numpy** a été conçu comme une boîte à outils fonctionnelle à une époque (version initiale = 1995) où le langage Python n'intégrait pas encore les fonctionnalités du paradigme 'objet'. Alors que **pandas** a été développé beaucoup plus récemment (version initiale = 2010) lorsque Python était devenu un langage objet très avancé. Pour l'utilisateur, cette différence d'architecture implique une différence dans le flux de travail (*workflow*) : avec **numpy** on enchaine des appels de fonctions en passant les matrices généralement en tant que premier argument de la fonction, alors qu'avec **pandas**, on enchaine les traitements sur un jeu de données par des compositions de méthodes, via la notation pointée.

---
### 1 - Informations générales sur les données stockées

In [452]:
dd.head(3) # affichage des 'n' premières lignes (5 par défaut)
dd.tail(1) # affichage des 'n' dernières lignes (5 par défaut)

    Name Model  Start  Stop  Score   Test       Date     Delta
AAA  AAA     S      0    67    0.0  False 2000-01-01 8366 days
BBB  BBB     M      0    31    0.6  False 2000-02-01 8335 days
CCC  CCC     L      0     3    1.2  False 2000-03-01 8306 days

    Name Model  Start  Stop  Score  Test       Date     Delta
FFF  FFF     L      0    51    3.0  True 2000-06-01 8214 days

In [453]:
dd.info() # informations générales concernant l'implémentation

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, AAA to FFF
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Model   6 non-null      category
 2   Start   6 non-null      int64
 3   Stop    6 non-null      uint8
 4   Score   6 non-null      float64
 5   Test    6 non-null      bool
 6   Date    6 non-null      datetime64[ns]
 7   Delta   6 non-null      timedelta64[ns]
dtypes: bool(1), category(1), datetime64[ns](1), float64(1), int64(1), object(1), timedelta64[ns](1), uint8(1)
memory usage: 438.0+ bytes

In [454]:
dd.describe() # statistiques descriptives sur chaque colonne à valeurs numériques

       Start       Stop     Score                       Delta
count    6.0   6.000000  6.000000                           6
mean     0.0  31.166667  1.500000          8290 days 04:00:00
std      0.0  23.853022  1.122497  56 days 17:09:17.293801904
min      0.0   3.000000  0.000000          8214 days 00:00:00
25%      0.0  17.250000  0.750000          8252 days 12:00:00
50%      0.0  24.500000  1.500000          8290 days 12:00:00
75%      0.0  46.000000  2.250000          8327 days 18:00:00
max      0.0  67.000000  3.000000          8366 days 00:00:00

In [192]:
dd.describe(include='all', datetime_is_numeric=True) # on force l'inclusion des colonnes non-numériques

,Name,Model,Start,Stop,Score,Test,Date,Delta
count,6,6,6.0,6.000000,6.000000,6,6,6
unique,6,3,NaN,NaN,NaN,2,NaN,NaN
top,AAA,L,NaN,NaN,NaN,False,NaN,NaN
freq,1,2,NaN,NaN,NaN,3,NaN,NaN
mean,NaN,NaN,0.0,48.666667,1.500000,NaN,2000-03-16 20:00:00,8289 days 04:00:00
min,NaN,NaN,0.0,8.000000,0.000000,NaN,2000-01-01 00:00:00,8213 days 00:00:00
25%,NaN,NaN,0.0,18.250000,0.750000,NaN,2000-02-08 06:00:00,8251 days 12:00:00
50%,NaN,NaN,0.0,58.500000,1.500000,NaN,2000-03-16 12:00:00,8289 days 12:00:00
75%,NaN,NaN,0.0,74.750000,2.250000,NaN,2000-04-23 12:00:00,8326 days 18:00:00
max,NaN,NaN,0.0,82.000000,3.000000,NaN,2000-06-01 00:00:00,8365 days 00:00:00
std,NaN,NaN,0.0,33.547976,1.122497,NaN,NaN,56 days 17:09:17.293801904

---
### 2 - Extraction de données

Parmi les opérations les plus fréquentes dans la manipulation des tables, figure l'extraction d'un sous-ensemble des données, soit sous la forme d'une zone rectangulaire (définie par une ***double tranche***), soit sous la forme d'une sélection conjointe de lignes et de colonnes (définie par une ***double énumération***), soit sous la forme d'un ensemble de contraintes (définies par des ***prédicats simple ou multiples***). Avec le mécanisme d'indexation fourni par **pandas** toutes ces opérations sont très simples à mettre en oeuvre :

In [193]:
dd # rappel du contenu de la table

    Name Model  Start  Stop  Score   Test       Date     Delta
AAA  AAA     S      0    43    0.0  False 2000-01-01 8365 days
BBB  BBB     M      0    75    0.6  False 2000-02-01 8334 days
CCC  CCC     L      0    74    1.2  False 2000-03-01 8305 days
DDD  DDD     S      0    82    1.8   True 2000-04-01 8274 days
EEE  EEE     M      0     8    2.4   True 2000-05-01 8244 days
FFF  FFF     L      0    10    3.0   True 2000-06-01 8213 days

In [194]:
show("dd['CCC':'EEE'].T['Model':'Test'].T#;") # accès avec double tranche de labels
show("dd.loc['CCC':'EEE','Model':'Test']#;") # idem avec 'loc'
show("dd.iloc[2:5,1:6]#;") # idem avec 'iloc' (double tranche de positions)

show("dd.T[['FFF','AAA','DDD']].T[['Date','Score','Model']]#;") # double énumération de  labels
show("dd.loc[('FFF','AAA','DDD'),('Date','Score','Model')]#;") # idem avec 'loc'
show("dd.iloc[[5,0,3],[6,4,1]]#") # idem avec 'iloc' (double énumération de positions)

dd['CCC':'EEE'].T['Model':'Test'].T =
    Model Start Stop Score   Test
CCC     L     0   74   1.2  False
DDD     S     0   82   1.8   True
EEE     M     0    8   2.4   True

dd.loc['CCC':'EEE','Model':'Test'] =
    Model  Start  Stop  Score   Test
CCC     L      0    74    1.2  False
DDD     S      0    82    1.8   True
EEE     M      0     8    2.4   True

dd.iloc[2:5,1:6] =
    Model  Start  Stop  Score   Test
CCC     L      0    74    1.2  False
DDD     S      0    82    1.8   True
EEE     M      0     8    2.4   True

dd.T[['FFF','AAA','DDD']].T[['Date','Score','Model']] =
          Date Score Model
FFF 2000-06-01   3.0     L
AAA 2000-01-01   0.0     S
DDD 2000-04-01   1.8     S

dd.loc[('FFF','AAA','DDD'),('Date','Score','Model')] =
          Date  Score Model
FFF 2000-06-01    3.0     L
AAA 2000-01-01    0.0     S
DDD 2000-04-01    1.8     S

dd.iloc[[5,0,3],[6,4,1]] =
          Date  Score Model
FFF 2000-06-01    3.0     L
AAA 2000-01-01    0.0     S
DDD 2000-04-01    1.8     S

In [195]:
show("dd.Score > 1.5#;") # création d'un prédicat sur une colonne (notation pointée)
show("(dd.Model == 'S') & (dd.Score > 1.5)#;") # idem sur plusieurs colonnes (parenthèses obligatoires)
show("dd[dd.Model == 'S']#;") # extraction des lignes vérifiant un prédicat
show("dd[dd.Model == 'S'].Score#;") # idem avec sélection d'une seule colonne (notation pointée)
show("dd[dd.Model == 'S']['Date Test Score'.split()]#") # idem avec sélection de plusieurs colonnes

dd.Score > 1.5 =
AAA    False
BBB    False
CCC    False
DDD     True
EEE     True
FFF     True
Name: Score, dtype: bool

(dd.Model == 'S') & (dd.Score > 1.5) =
AAA    False
BBB    False
CCC    False
DDD     True
EEE    False
FFF    False
dtype: bool

dd[dd.Model == 'S'] =
    Name Model  Start  Stop  Score   Test       Date     Delta
AAA  AAA     S      0    43    0.0  False 2000-01-01 8365 days
DDD  DDD     S      0    82    1.8   True 2000-04-01 8274 days

dd[dd.Model == 'S'].Score =
AAA    0.0
DDD    1.8
Name: Score, dtype: float64

dd[dd.Model == 'S']['Date Test Score'.split()] =
          Date   Test  Score
AAA 2000-01-01  False    0.0
DDD 2000-04-01   True    1.8

In [322]:
show("'S' in dd.Model; 'S' in dd.Model.values;") # par défaut, 'in' s'applique à l'index
show("dd[dd.Model.isin({'L','M'})]#") # extraction de lignes avec un prédicat d'inclusion dans un ensemble

'S' in dd.Model = False
'S' in dd.Model.values = True

dd[dd.Model.isin({'L','M'})] =
    Name Model  Start  Stop  Score   Test  Rank  Final  Color
BBB  BBB     M    0.0  27.0    0.6  False   5.0   16.2    NaN
CCC  CCC     L    NaN  72.0    1.2  False   4.0   86.4  green
FFF  FFF     L    0.0  74.0    3.0   True   1.0  222.0    NaN

---
### 3 - Insertion, Suppression et Modification de données

Pour éviter de détruire des données par erreur, la plupart des commandes de **pandas** qui suppriment ou modifient les données vont travailler sur une copie des données originelles, ce qui permet de tester sans risques les opérations à effectuer avant de les mettre concrètement en oeuvre. Ainsi la plupart des fonctions possède un argument booléen **`inplace`** (égal à **`False`** par défaut) qui indique ***si la fonction doit s'appliquer "sur place" ou sur une copie***. Les commandes d'insertion de données, par contre, n'ont besoin de ce mécanisme, puisque les données existantes ne sont pas modifiées.

In [466]:
# on remet les instructions de création de la table 'dd', car on va la modifier à plusieurs reprises
dd = pd.DataFrame(dict(Name=[3*c for c in 'ABCDEF'], Model=pd.Categorical(2*['S','M','L']), Start=0,
     Stop=np.random.randint(0,100,(6,), dtype='u1'), Score=np.linspace(0, 3, 6), Test=dates.month > 3, 
     Date=dates, Delta=(pd.Timestamp('now') - dates).round('D')))
dd.index = dd.Name; dd.index.name = None; dd

    Name Model  Start  Stop  Score   Test       Date     Delta
AAA  AAA     S      0    16    0.0  False 2000-01-01 8366 days
BBB  BBB     M      0    38    0.6  False 2000-02-01 8335 days
CCC  CCC     L      0    63    1.2  False 2000-03-01 8306 days
DDD  DDD     S      0    24    1.8   True 2000-04-01 8275 days
EEE  EEE     M      0    76    2.4   True 2000-05-01 8245 days
FFF  FFF     L      0    78    3.0   True 2000-06-01 8214 days

In [467]:
dd['Rank'] = range(6,0,-1) # insertion d'une colonne complète
dd['Final'] = dd.Stop * dd.Score # insertion d'une colonne complète par combinaison
dd['Color'] = pd.Series(dict(AAA='blue', CCC='green', DDD='red')) # insertion d'une colonne incomplète
dd['Color-Name'] = dd.Color + '-' + dd.Name # insertion d'une colonne incomplète par combinaison
dd # note : la valeur NaN est "contagieuse" (elle se transmet à toute opération où elle est impliquée)

,Name,Model,Start,Stop,Score,Test,Date,Delta,Rank,Final,Color,Color-Name
AAA,AAA,S,0,16,0.0,False,2000-01-01,8366 days,6,0.0,blue,blue-AAA
BBB,BBB,M,0,38,0.6,False,2000-02-01,8335 days,5,22.8,NaN,NaN
CCC,CCC,L,0,63,1.2,False,2000-03-01,8306 days,4,75.6,green,green-CCC
DDD,DDD,S,0,24,1.8,True,2000-04-01,8275 days,3,43.2,red,red-DDD
EEE,EEE,M,0,76,2.4,True,2000-05-01,8245 days,2,182.4,NaN,NaN
FFF,FFF,L,0,78,3.0,True,2000-06-01,8214 days,1,234.0,NaN,NaN

In [468]:
del dd['Color-Name'] # suppression d'une colonne (sur place)
dd.drop(columns=['Date','Delta']) # suppression d'un groupe de colonnes (sur copie)
dd # les colonnes n'ont pas été supprimées
dd.drop(columns=['Date','Delta'], inplace=True) # suppression d'un groupe de colonnes (sur place)
dd # maintenant, oui...

    Name Model  Start  Stop  Score   Test  Rank  Final  Color
AAA  AAA     S      0    16    0.0  False     6    0.0   blue
BBB  BBB     M      0    38    0.6  False     5   22.8    NaN
CCC  CCC     L      0    63    1.2  False     4   75.6  green
DDD  DDD     S      0    24    1.8   True     3   43.2    red
EEE  EEE     M      0    76    2.4   True     2  182.4    NaN
FFF  FFF     L      0    78    3.0   True     1  234.0    NaN

,Name,Model,Start,Stop,Score,Test,Date,Delta,Rank,Final,Color
AAA,AAA,S,0,16,0.0,False,2000-01-01,8366 days,6,0.0,blue
BBB,BBB,M,0,38,0.6,False,2000-02-01,8335 days,5,22.8,NaN
CCC,CCC,L,0,63,1.2,False,2000-03-01,8306 days,4,75.6,green
DDD,DDD,S,0,24,1.8,True,2000-04-01,8275 days,3,43.2,red
EEE,EEE,M,0,76,2.4,True,2000-05-01,8245 days,2,182.4,NaN
FFF,FFF,L,0,78,3.0,True,2000-06-01,8214 days,1,234.0,NaN

    Name Model  Start  Stop  Score   Test  Rank  Final  Color
AAA  AAA     S      0    16    0.0  False     6    0.0   blue
BBB  BBB     M      0    38    0.6  False     5   22.8    NaN
CCC  CCC     L      0    63    1.2  False     4   75.6  green
DDD  DDD     S      0    24    1.8   True     3   43.2    red
EEE  EEE     M      0    76    2.4   True     2  182.4    NaN
FFF  FFF     L      0    78    3.0   True     1  234.0    NaN

In [469]:
# insertion d'une ligne incomplète (à cause du NaN, la colonne 'Stop' est transformée en 'float')
dd.loc['ZZZ'] = dict(Name='ZZZ', Model='S', Start=1, Test=False, Color='white')
dd

    Name Model  Start  Stop  Score   Test  Rank  Final  Color
AAA  AAA     S      0  16.0    0.0  False   6.0    0.0   blue
BBB  BBB     M      0  38.0    0.6  False   5.0   22.8    NaN
CCC  CCC     L      0  63.0    1.2  False   4.0   75.6  green
DDD  DDD     S      0  24.0    1.8   True   3.0   43.2    red
EEE  EEE     M      0  76.0    2.4   True   2.0  182.4    NaN
FFF  FFF     L      0  78.0    3.0   True   1.0  234.0    NaN
ZZZ  ZZZ     S      1   NaN    NaN  False   NaN    NaN  white

In [470]:
ee = dd.drop(['BBB','DDD','EEE']) # suppression de lignes (sur copie)
ee
dd.drop('EEE', inplace=True) # suppression d'une ligne (sur place)
dd

    Name Model  Start  Stop  Score   Test  Rank  Final  Color
AAA  AAA     S      0  16.0    0.0  False   6.0    0.0   blue
CCC  CCC     L      0  63.0    1.2  False   4.0   75.6  green
FFF  FFF     L      0  78.0    3.0   True   1.0  234.0    NaN
ZZZ  ZZZ     S      1   NaN    NaN  False   NaN    NaN  white

    Name Model  Start  Stop  Score   Test  Rank  Final  Color
AAA  AAA     S      0  16.0    0.0  False   6.0    0.0   blue
BBB  BBB     M      0  38.0    0.6  False   5.0   22.8    NaN
CCC  CCC     L      0  63.0    1.2  False   4.0   75.6  green
DDD  DDD     S      0  24.0    1.8   True   3.0   43.2    red
FFF  FFF     L      0  78.0    3.0   True   1.0  234.0    NaN
ZZZ  ZZZ     S      1   NaN    NaN  False   NaN    NaN  white

---
Pour la modification individuelle d'un élément d'une table, il existe ***une erreur de débutant assez courante***, due au système d'indexation différent utilisé par **pandas** et **numpy** :

In [471]:
ee[2,2] = 3 # on a l'impression de modifier un élément de la table, comme en 'numpy'
ee['FFF','Color'] = 'yellow' # idem en utilisant les labels
ee # ATTENTION : ce n'est pas le cas, car 'pandas' n'est pas 'numpy'

,Name,Model,Start,Stop,Score,Test,Rank,Final,Color,"(2, 2)","(FFF, Color)"
AAA,AAA,S,0,16.0,0.0,False,6.0,0.0,blue,3,yellow
CCC,CCC,L,0,63.0,1.2,False,4.0,75.6,green,3,yellow
FFF,FFF,L,0,78.0,3.0,True,1.0,234.0,NaN,3,yellow
ZZZ,ZZZ,S,1,NaN,NaN,False,NaN,NaN,white,3,yellow

In [472]:
# il faut utiliser les accesseurs 'loc' et/ou 'iloc' pour ce type de modification
dd.loc['FFF','Color'] = 'yellow' # modification d'un élément individuel (en utilisant les labels)
dd.iloc[2,2] = 3 # idem en utilisant les positions
dd # ces deux modifications sont systématiquement "sur place"

    Name Model  Start  Stop  Score   Test  Rank  Final   Color
AAA  AAA     S      0  16.0    0.0  False   6.0    0.0    blue
BBB  BBB     M      0  38.0    0.6  False   5.0   22.8     NaN
CCC  CCC     L      3  63.0    1.2  False   4.0   75.6   green
DDD  DDD     S      0  24.0    1.8   True   3.0   43.2     red
FFF  FFF     L      0  78.0    3.0   True   1.0  234.0  yellow
ZZZ  ZZZ     S      1   NaN    NaN  False   NaN    NaN   white

In [473]:
dd.loc['FFF','Color'] = np.nan # mettre 'np.nan' signifie effacer la donnée pour 'pandas'
dd.iloc[2,2] = None # idem avec 'None' (à nouveau, la colonne avec NaN est transformée en 'float')
dd

    Name Model  Start  Stop  Score   Test  Rank  Final  Color
AAA  AAA     S    0.0  16.0    0.0  False   6.0    0.0   blue
BBB  BBB     M    0.0  38.0    0.6  False   5.0   22.8    NaN
CCC  CCC     L    NaN  63.0    1.2  False   4.0   75.6  green
DDD  DDD     S    0.0  24.0    1.8   True   3.0   43.2    red
FFF  FFF     L    0.0  78.0    3.0   True   1.0  234.0    NaN
ZZZ  ZZZ     S    1.0   NaN    NaN  False   NaN    NaN  white

---
Le package **pandas** fournit plusieurs outils pour combler les données manquantes dans une série ou une table :

In [474]:
show("dd.Color.fillna('black')#;") # remplacement des NaN par une valeur constante
show("dd.Score.fillna(dd.Score.mean())#;") # remplacement des NaN par une valeur calculée
show("dd.Color.fillna(method='ffill')#;") # remplacement des NaN par la valeur précédente (forward fill)
show("dd.Color.fillna(method='bfill')#;") # remplacement des NaN par la valeur suivante (backward fill)
dd # ATTENTION : la table est inchangée (pas de 'inplace=True' lors des appels de fonctions)

dd.Color.fillna('black') =
AAA     blue
BBB    black
CCC    green
DDD      red
FFF    black
ZZZ    white
Name: Color, dtype: object

dd.Score.fillna(dd.Score.mean()) =
AAA    0.00
BBB    0.60
CCC    1.20
DDD    1.80
FFF    3.00
ZZZ    1.32
Name: Score, dtype: float64

dd.Color.fillna(method='ffill') =
AAA     blue
BBB     blue
CCC    green
DDD      red
FFF      red
ZZZ    white
Name: Color, dtype: object

dd.Color.fillna(method='bfill') =
AAA     blue
BBB    green
CCC    green
DDD      red
FFF    white
ZZZ    white
Name: Color, dtype: object

    Name Model  Start  Stop  Score   Test  Rank  Final  Color
AAA  AAA     S    0.0  16.0    0.0  False   6.0    0.0   blue
BBB  BBB     M    0.0  38.0    0.6  False   5.0   22.8    NaN
CCC  CCC     L    NaN  63.0    1.2  False   4.0   75.6  green
DDD  DDD     S    0.0  24.0    1.8   True   3.0   43.2    red
FFF  FFF     L    0.0  78.0    3.0   True   1.0  234.0    NaN
ZZZ  ZZZ     S    1.0   NaN    NaN  False   NaN    NaN  white

---
### 4 - Classements et regroupements de données

La dernière catégorie des opérations de manipulation inclut tout ce qui concerne les classements de données selon des critères variées, les regroupements externes (= concaténation ou fusion de plusieurs séries ou tables en une seule) ou les regroupements internes (= partitionnement des données selon un ou plusieurs critères). A la différence de **numpy**, le package **pandas** fournit des opérations très complète dans cette catégorie, la plupart étant inspiré des [**Systèmes de Gestion de Bases de Données Relationnelles**](https://fr.wikipedia.org/wiki/Base_de_donn%C3%A9es_relationnelle), et du langage de requêtes [**SQL**](https://fr.wikipedia.org/wiki/Structured_Query_Language). Pour illustrer ces outils, on va créer de nouvelles tables, avec une structure plus intéressante pour ce type de manipulations :

In [652]:
np.random.seed(0); values = np.random.randint(0, 10, (8,2))
names = np.array([3*c for c in 'ABCDEFBGECH']); chars = list('XYZZXZYXXZYyzyxxzzzyyx')
ee = pd.DataFrame(dict(A=values[:6,0], B=values[:6,1], C=chars[:6], D=chars[11:17]), index=names[:6])
ee.iloc[2::2,1] = ee.iloc[1,2] = ee.iloc[0,0] = np.nan # on rajoute quelques valeurs NaN
ee
ff = pd.DataFrame(dict(C=chars[6:11], D=chars[17:], E=values[-5:,0], F=values[-5:,1]), index=names[6:])
ff

       A    B    C  D
AAA  NaN  0.0    X  y
BBB  3.0  3.0  NaN  z
CCC  7.0  NaN    Z  y
DDD  3.0  5.0    Z  x
EEE  2.0  NaN    X  x
FFF  7.0  6.0    Z  z

     C  D  E  F
BBB  Y  z  3  5
GGG  X  z  2  4
EEE  X  y  7  6
CCC  Z  y  8  8
HHH  Y  x  1  6

In [653]:
show("ff.sort_index()#;") # tri (ascendant, par défaut) de la table selon l'index
show("ee.sort_values(by='B')#;") # tri de la table selon une colonne spécifique
show("ee.sort_values(by=['C','B'], ascending=False)#;") # tri (descendant) selon un groupe de colonnes
# les valeurs NaN sont toujours mises à la fin de chaque groupe, en tri ascendant ou en descendant

ff.sort_index() =
     C  D  E  F
BBB  Y  z  3  5
CCC  Z  y  8  8
EEE  X  y  7  6
GGG  X  z  2  4
HHH  Y  x  1  6

ee.sort_values(by='B') =
       A    B    C  D
AAA  NaN  0.0    X  y
BBB  3.0  3.0  NaN  z
DDD  3.0  5.0    Z  x
FFF  7.0  6.0    Z  z
CCC  7.0  NaN    Z  y
EEE  2.0  NaN    X  x

ee.sort_values(by=['C','B'], ascending=False) =
       A    B    C  D
FFF  7.0  6.0    Z  z
DDD  3.0  5.0    Z  x
CCC  7.0  NaN    Z  y
AAA  NaN  0.0    X  y
EEE  2.0  NaN    X  x
BBB  3.0  3.0  NaN  z

In [654]:
show("ee#;;(2*ee.A + 4*ee.B).sort_values()#;") # on peut trier sur des combinaisons de colonnes
show("(2*ee.A.fillna(ee.A.max()) + 4*ee.B.fillna(ee.A)).sort_values()#") # et même en remplissant les NaN

ee =
       A    B    C  D
AAA  NaN  0.0    X  y
BBB  3.0  3.0  NaN  z
CCC  7.0  NaN    Z  y
DDD  3.0  5.0    Z  x
EEE  2.0  NaN    X  x
FFF  7.0  6.0    Z  z

(2*ee.A + 4*ee.B).sort_values() =
BBB    18.0
DDD    26.0
FFF    38.0
AAA     NaN
CCC     NaN
EEE     NaN
dtype: float64

(2*ee.A.fillna(ee.A.max()) + 4*ee.B.fillna(ee.A)).sort_values() =
EEE    12.0
AAA    14.0
BBB    18.0
DDD    26.0
FFF    38.0
CCC    42.0
dtype: float64

In [655]:
show("ee.A#;; ee.A.rank()#;") # rang des éléments d'une colonne (dans l'ordre croissant des valeurs)
show("ee.A.rank(method='min')#;; ee.A.rank(method='dense')#;") # méthodes de gestion des rangs identiques

ee.A =
AAA    NaN
BBB    3.0
CCC    7.0
DDD    3.0
EEE    2.0
FFF    7.0
Name: A, dtype: float64

ee.A.rank() =
AAA    NaN
BBB    2.5
CCC    4.5
DDD    2.5
EEE    1.0
FFF    4.5
Name: A, dtype: float64

ee.A.rank(method='min') =
AAA    NaN
BBB    2.0
CCC    4.0
DDD    2.0
EEE    1.0
FFF    4.0
Name: A, dtype: float64

ee.A.rank(method='dense') =
AAA    NaN
BBB    2.0
CCC    3.0
DDD    2.0
EEE    1.0
FFF    3.0
Name: A, dtype: float64

In [656]:
show("ee.A#;; ee.A.value_counts()#;") # compteur d'occurrences sur une colonne (ordre décroissant)
show("ee.A.value_counts(normalize=True)#;") # idem mais transformation en probabilités
show("ff.E#;; pd.qcut(ff.E, 3, labels=['low','mid','high'])#") # découpage par tranche de quantiles

ee.A =
AAA    NaN
BBB    3.0
CCC    7.0
DDD    3.0
EEE    2.0
FFF    7.0
Name: A, dtype: float64

ee.A.value_counts() =
3.0    2
7.0    2
2.0    1
Name: A, dtype: int64

ee.A.value_counts(normalize=True) =
3.0    0.4
7.0    0.4
2.0    0.2
Name: A, dtype: float64

ff.E =
BBB    3
GGG    2
EEE    7
CCC    8
HHH    1
Name: E, dtype: int32

pd.qcut(ff.E, 3, labels=['low','mid','high']) =
BBB     mid
GGG     low
EEE    high
CCC    high
HHH     low
Name: E, dtype: category
Categories (3, object): ['low' < 'mid' < 'high']

---
Les opérations de regroupements externes utilisent deux fonctions principales **`concat`** et **`merge`** :

In [657]:
pd.concat((ee,ff)) # concaténation des index sur les lignes, union des index sur les colonnes
pd.concat((ee,ff), join='inner') # idem avec intersection des index sur les colonnes
pd.concat((ee,ff), axis=1) # concaténation des index sur les colonnes, union des index sur les lignes
pd.concat((ee,ff), axis=1, join='inner') # idem avec intersection des index sur les lignes

       A    B    C  D    E    F
AAA  NaN  0.0    X  y  NaN  NaN
BBB  3.0  3.0  NaN  z  NaN  NaN
CCC  7.0  NaN    Z  y  NaN  NaN
DDD  3.0  5.0    Z  x  NaN  NaN
EEE  2.0  NaN    X  x  NaN  NaN
FFF  7.0  6.0    Z  z  NaN  NaN
BBB  NaN  NaN    Y  z  3.0  5.0
GGG  NaN  NaN    X  z  2.0  4.0
EEE  NaN  NaN    X  y  7.0  6.0
CCC  NaN  NaN    Z  y  8.0  8.0
HHH  NaN  NaN    Y  x  1.0  6.0

       C  D
AAA    X  y
BBB  NaN  z
CCC    Z  y
DDD    Z  x
EEE    X  x
FFF    Z  z
BBB    Y  z
GGG    X  z
EEE    X  y
CCC    Z  y
HHH    Y  x

       A    B    C    D    C    D    E    F
AAA  NaN  0.0    X    y  NaN  NaN  NaN  NaN
BBB  3.0  3.0  NaN    z    Y    z  3.0  5.0
CCC  7.0  NaN    Z    y    Z    y  8.0  8.0
DDD  3.0  5.0    Z    x  NaN  NaN  NaN  NaN
EEE  2.0  NaN    X    x    X    y  7.0  6.0
FFF  7.0  6.0    Z    z  NaN  NaN  NaN  NaN
GGG  NaN  NaN  NaN  NaN    X    z  2.0  4.0
HHH  NaN  NaN  NaN  NaN    Y    x  1.0  6.0

       A    B    C  D  C  D  E  F
BBB  3.0  3.0  NaN  z  Y  z  3  5
CCC  7.0  NaN    Z  y  Z  y  8  8
EEE  2.0  NaN    X  x  X  y  7  6

In [658]:
pd.merge(ee, ff, left_index=True, right_index=True) # idem 'concat inner' mais avec gestion des collisions
gg = pd.merge(ee, ff, how='outer', left_index=True, right_index=True) # idem 'concat outer' avec gestion
gg # c'est généralement 'merge outer' qui est le plus intéressant dans les regroupements externes

       A    B  C_x D_x C_y D_y  E  F
BBB  3.0  3.0  NaN   z   Y   z  3  5
CCC  7.0  NaN    Z   y   Z   y  8  8
EEE  2.0  NaN    X   x   X   y  7  6

       A    B  C_x  D_x  C_y  D_y    E    F
AAA  NaN  0.0    X    y  NaN  NaN  NaN  NaN
BBB  3.0  3.0  NaN    z    Y    z  3.0  5.0
CCC  7.0  NaN    Z    y    Z    y  8.0  8.0
DDD  3.0  5.0    Z    x  NaN  NaN  NaN  NaN
EEE  2.0  NaN    X    x    X    y  7.0  6.0
FFF  7.0  6.0    Z    z  NaN  NaN  NaN  NaN
GGG  NaN  NaN  NaN  NaN    X    z  2.0  4.0
HHH  NaN  NaN  NaN  NaN    Y    x  1.0  6.0

Après un **`concat`** ou un **`merge`**, il faut généralement fait un peu de polissage manuel sur les tables obtenues. Dans notre exemple, on suppose que les deux colonnes **C_x** (provenant de la table **ee**) et **C_y** (provenant de la table **ff**) représentent les mêmes paramètres, donc on aimerait bien les fusionner. Pour cela, il faut d'abord vérifier qu'il n'y a pas d'incompatibilité : il ne faut pas qu'il existe de ligne où les valeurs des colonnes **C_x** et **C_y** sont à la fois non vides et différentes. Il faut également faire la même vérification pour les colonnes **D_x** et **D_y** que l'on aimerait fusionner également :

In [659]:
gg["C_x C_y D_x D_y".split()] # on peut vérifier les incompatibilités visuellement
# ou alors on fait faire la recherche à 'pandas'
gg[gg.C_x.notnull() & gg.C_y.notnull() & (gg.C_x != gg.C_y)] # recherche d'incompatibilités sur C_x/C_y
gg[gg.D_x.notnull() & gg.D_y.notnull() & (gg.D_x != gg.D_y)] # idem sur D_x/D_y

     C_x  C_y  D_x  D_y
AAA    X  NaN    y  NaN
BBB  NaN    Y    z    z
CCC    Z    Z    y    y
DDD    Z  NaN    x  NaN
EEE    X    X    x    y
FFF    Z  NaN    z  NaN
GGG  NaN    X  NaN    z
HHH  NaN    Y  NaN    x

Empty DataFrame
Columns: [A, B, C_x, D_x, C_y, D_y, E, F]
Index: []

       A   B C_x D_x C_y D_y    E    F
EEE  2.0 NaN   X   x   X   y  7.0  6.0

Au final, pas d'incompatibilité pour fusionner **C_x** et **C_y**, par contre, la ligne **EEE** possède des valeurs différente pour **D_x** et **D_y**, il faut donc choisir celle qu'on va retenir lors de la fusion des colonnes :

In [660]:
gg.C_x.fillna(gg.C_y, inplace=True) # on remplit les NaN de 'C_x' par les valeurs correspondantes de 'C_y'
gg.D_x.fillna(gg.D_y, inplace=True) # on remplit les NaN de 'D_x' par les valeurs correspondantes de 'D_y'
gg.rename({'C_x':'C'}, axis=1, inplace=True); del gg['C_y'] # on renomme 'C_x' en 'C' et on supprime 'C_y'
gg.rename({'D_x':'D'}, axis=1, inplace=True); del gg['D_y'] # on renomme 'D_x' en 'C' et on supprime 'D_y'
gg

       A    B  C  D    E    F
AAA  NaN  0.0  X  y  NaN  NaN
BBB  3.0  3.0  Y  z  3.0  5.0
CCC  7.0  NaN  Z  y  8.0  8.0
DDD  3.0  5.0  Z  x  NaN  NaN
EEE  2.0  NaN  X  x  7.0  6.0
FFF  7.0  6.0  Z  z  NaN  NaN
GGG  NaN  NaN  X  z  2.0  4.0
HHH  NaN  NaN  Y  x  1.0  6.0

De même, on peut considérer que la colonne **E** est similaire à la colonne **A**, donc on peut compléter les données manquantes de **E** par les données correspondantes dans **A** et vice-versa (et idem pour les colonnes **B** et **F**). Ces opérations s'appellent des **complétions croisées** et après leur utilisation, il n'y a quasiment plus de valeurs manquantes dans la table fusionnée :

In [661]:
gg.A.fillna(gg.E, inplace=True); gg.E.fillna(gg.A, inplace=True) # complétion croisée pour A et E
gg.B.fillna(gg.F, inplace=True); gg.F.fillna(gg.B, inplace=True) # complétion croisée pour B et F
gg # il n'y a presque plus de NaN

       A    B  C  D    E    F
AAA  NaN  0.0  X  y  NaN  0.0
BBB  3.0  3.0  Y  z  3.0  5.0
CCC  7.0  8.0  Z  y  8.0  8.0
DDD  3.0  5.0  Z  x  3.0  5.0
EEE  2.0  6.0  X  x  7.0  6.0
FFF  7.0  6.0  Z  z  7.0  6.0
GGG  2.0  4.0  X  z  2.0  4.0
HHH  1.0  6.0  Y  x  1.0  6.0

---
Les opérations de regroupements internes utilisent deux fonctions principales **`groupby`** et **`pivot_table`**. La première permet d'effecter des statistiques sur des regroupements d'éléments effectués en fonction d'un critère de classification. La seconde permet de comparer l'influence relative de deux critères de classification sur les données des autres colonnes :

In [686]:
gC, gD = gg.groupby(by='C'), gg.groupby(by='D')
show("gC.ngroups; gC.size()#;; gC.mean().round(2)#;; gD.ngroups; gD.size()#;; gD.max()#")

gC.ngroups = 3
gC.size() =
C
X    3
Y    2
Z    3
dtype: int64

gC.mean().round(2) =
      A     B    E     F
C
X  2.00  3.33  4.5  3.33
Y  2.00  4.50  2.0  5.50
Z  5.67  6.33  6.0  6.33

gD.ngroups = 3
gD.size() =
D
x    3
y    2
z    3
dtype: int64

gD.max() =
     A    B  C    E    F
D
x  3.0  6.0  Z  7.0  6.0
y  7.0  8.0  Z  8.0  8.0
z  7.0  6.0  Z  7.0  6.0

In [662]:
pd.pivot_table(gg, index='D', columns='C', values='A B E F'.split())

     A              B              E              F
C    X    Y    Z    X    Y    Z    X    Y    Z    X    Y    Z
D
x  2.0  1.0  3.0  6.0  6.0  5.0  7.0  1.0  3.0  6.0  6.0  5.0
y  NaN  NaN  7.0  0.0  NaN  8.0  NaN  NaN  8.0  0.0  NaN  8.0
z  2.0  3.0  7.0  4.0  3.0  6.0  2.0  3.0  7.0  4.0  5.0  6.0

<h2 style="padding:16px; color:#FFF; background:#07D">C - Lecture et écriture sur disque</h2>

TODO

In [12]:
csv = pd.read_csv('TEST/test-CSV.csv') # lecture d'un fichier CSV et transformation en 'dataframe'
csv

,Nom,Prénom,Date de naissance,Lieu de naissance,Date de décès,Lieu de décès
0,Hugo,Victor,26/02/1802,Besançon,22/05/1885,Paris
1,Baudelaire,Charles,09/04/1821,Paris,31/08/1867,Paris
2,Rimbaud,Arthur,20/10/1854,Charleville,10/11/1891,Marseille

In [25]:
json = pd.read_json('TEST/test-JSON.json')
json
n = json.Naissance.str.split(expand=True)
d = json['Décès'].str.split(expand=True) # à cause des accents, la notation pointée ne fonctionne pas
json['Date de naissance'] = n[0]; json['Lieu de naissance'] = n[1]; del json['Naissance']
json['Date de décès'] = d[0]; json['Lieu de décès'] = d[1]; del json['Décès']
json

          Nom   Prénom               Naissance                 Décès
0        Hugo   Victor     26/02/1802 Besançon      22/05/1885 Paris
1  Baudelaire  Charles        09/04/1821 Paris      31/08/1867 Paris
2     Rimbaud   Arthur  20/10/1854 Charleville  10/11/1891 Marseille

,Nom,Prénom,Date de naissance,Lieu de naissance,Date de décès,Lieu de décès
0,Hugo,Victor,26/02/1802,Besançon,22/05/1885,Paris
1,Baudelaire,Charles,09/04/1821,Paris,31/08/1867,Paris
2,Rimbaud,Arthur,20/10/1854,Charleville,10/11/1891,Marseille

In [11]:
authors = pd.read_html('TEST/test-HTML.html')
authors[0]

,Nom,Prénom,Date de naissance,Lieu de naissance,Date de décès,Lieu de décès
0,Hugo,Victor,26/02/1802,Besançon,22/05/1885,Paris
1,Baudelaire,Charles,09/04/1821,Paris,31/08/1867,Paris
2,Rimbaud,Arthur,20/10/1854,Charleville,10/11/1891,Marseille

In [ ]:
#pd.read_table

In [54]:
#authors.T.to_csv('test.csv') # écriture d'un dataframe dans un fichier CSV