<p style="color:#FFF; background:#07D; padding:12px; font-size:20px; font-style:italic; text-align:center">
<span style="width:49%; display:inline-block; text-align:left">Christophe Schlick</span>
<span style="width:49%; display:inline-block; text-align:right">schlick[at]u-bordeaux.fr</span>
<span style="font-size:48px; font-style:normal"><b>EXTRACTION&ensp;DE&ensp;DONNÉES</b></span><br>
<span style="width:49%; display:inline-block; text-align:left">Version 2024-09</span>
<span style="width:49%; display:inline-block; text-align:right">Licence CC-BY-NC-ND</span></p>

De nos jours, la plupart des jeux de données utilisés dans le domaine des Sciences des Données sont disponibles sur le web. Avec l'avènement du mouvement ***Open Data*** depuis une dizaine d'années, ces jeux de données sont regroupés sur des sites dédiés (j'en ai listé un certain nombre dans la page consacrée au sujet de projet) et facilement téléchargeables dans des formats standardisés, les plus fréquent étant les formats **CSV**, **JSON** et **XML**.

Néanmoins, il existe de très nombreuses données qui ne sont pas explicitement formatés pour être facilement téléchargées, la plupart du temps parce que ***leurs auteurs ont organisé ces données pour faciliter leur lecture sur une page web, mais pas forcément leur traitement par des outils d'automatisation***. Lorsqu'on souhaite récupérer et structurer ce type de données, il faut mettre en oeuvre des outils spécifiques, qui se regroupent dans deux catégories principales :

- Les outils de **web scraping** (en français, ***gratter ou racler le web***) permettent d'identifier et de récupérer des données spécifiques au sein d'une page web
- Les outils de **web crawling*** (en français, ***ramper ou crapahuter sur le web***) permettent de naviguer récursivement (soit en largeur, soit en profondeur) à partir d'une page web, en suivant certains des liens qui sont définis sur cette page

Les deux techniques combinées permettent de récupérer une énorme masse de données : globalement tout ce qui est affichable sur le web est récupérable avec ce type d'outils.

In [1]:
from SRC.tools import show, load, fetch
import pandas as pd

<h2 style="padding:16px; color:#FFF; background:#07D">A - load, fetch et pandas</h2>

In [2]:
# la fonction 'load' du module 'tools' permet de récupérer n'importe quel fichier texte via une URL
url = 'https://www.labri.fr/perso/schlick/outinfo/TEST/test-TXT.txt'
page = load(url) # on récupère le contenu sous forme de liste de lignes
print(page)

['Nom         Hugo', 'Prénom      Victor', 'Naissance   26/02/1802 Besançon', 'Décès       22/05/1885 Paris', 'Nom         Baudelaire', 'Prénom      Charles', 'Naissance   09/04/1821 Paris', 'Décès       31/08/1867 Paris', 'Nom         Rimbaud', 'Prénom      Arthur', 'Naissance   20/10/1854 Charleville', 'Décès       10/11/1891 Marseille']

In [3]:
# mais on peut garder le texte brut en mettant définissant l'argument split=''
page = load(url, split='') # on récupère sous forme de chaîne de caractères multi-lignes
print(page)

#
# Auteurs français du XIXe siècle
#

Nom         Hugo
Prénom      Victor
Naissance   26/02/1802 Besançon
Décès       22/05/1885 Paris

Nom         Baudelaire
Prénom      Charles
Naissance   09/04/1821 Paris
Décès       31/08/1867 Paris

Nom         Rimbaud
Prénom      Arthur
Naissance   20/10/1854 Charleville
Décès       10/11/1891 Marseille

In [4]:
# la même fonction 'load' permet de lire des fichiers CSV en appliquant un léger post-traitement*
url = 'https://www.labri.fr/perso/schlick/outinfo/TEST/test-CSV.csv'
page = load(url) # on récupère le contenu sous forme de liste de lignes
print(page, '\n')
data = [line.split(', ') for line in page] # conversion en liste de listes
print(data)

['Nom, Prénom, NaissanceDate, NaissanceLieu, DécèsDate, DécèsLieu', 'Hugo, Victor, 26/02/1802, Besançon, 22/05/1885, Paris', 'Baudelaire, Charles, 09/04/1821, Paris, 31/08/1867, Paris', 'Rimbaud, Arthur, 20/10/1854, Charleville, 10/11/1891, Marseille']

[['Nom', 'Prénom', 'NaissanceDate', 'NaissanceLieu', 'DécèsDate', 'DécèsLieu'], ['Hugo', 'Victor', '26/02/1802', 'Besançon', '22/05/1885', 'Paris'], ['Baudelaire', 'Charles', '09/04/1821', 'Paris', '31/08/1867', 'Paris'], ['Rimbaud', 'Arthur', '20/10/1854', 'Charleville', '10/11/1891', 'Marseille']]

In [5]:
# mais la fonction 'pd.read_csv' est plus souple pour ce genre de traitement
data = pd.read_csv(url, comment='#') # il faut définir le caractère préfixe utilisé pour les commentaires
data

          Nom    Prénom  NaissanceDate  NaissanceLieu    DécèsDate   DécèsLieu
0        Hugo    Victor     26/02/1802       Besançon   22/05/1885       Paris
1  Baudelaire   Charles     09/04/1821          Paris   31/08/1867       Paris
2     Rimbaud    Arthur     20/10/1854    Charleville   10/11/1891   Marseille

In [6]:
# le processus est très similaire pour les fichiers JSON
url = 'https://www.labri.fr/perso/schlick/outinfo/TEST/test-JSON.json'
page = load(url, split='') # on récupère sous forme de chaîne de caractères multi-lignes
print(page, '\n')
data = eval(page, {}, {}) # conversion en liste de dictionnaires
print(data)

[
  {
    "Nom" : "Hugo",
    "Prénom" : "Victor",
    "Naissance" : "26/02/1802 Besançon",
    "Décès" : "22/05/1885 Paris"
  },
  {
    "Nom" : "Baudelaire",
    "Prénom" : "Charles",
    "Naissance" : "09/04/1821 Paris",
    "Décès" : "31/08/1867 Paris"
  },
  {
    "Nom" : "Rimbaud",
    "Prénom" : "Arthur",
    "Naissance" : "20/10/1854 Charleville",
    "Décès" : "10/11/1891 Marseille"
  }
]

[{'Nom': 'Hugo', 'Prénom': 'Victor', 'Naissance': '26/02/1802 Besançon', 'Décès': '22/05/1885 Paris'}, {'Nom': 'Baudelaire', 'Prénom': 'Charles', 'Naissance': '09/04/1821 Paris', 'Décès': '31/08/1867 Paris'}, {'Nom': 'Rimbaud', 'Prénom': 'Arthur', 'Naissance': '20/10/1854 Charleville', 'Décès': '10/11/1891 Marseille'}]

In [7]:
# mais là encore, la fonction 'pd.read_json' simplifie le traitement
data = pd.read_json(url) # pas besoin de définir de préfixe de commentaire, car c'est impossible en JSON
data

          Nom   Prénom               Naissance                 Décès
0        Hugo   Victor     26/02/1802 Besançon      22/05/1885 Paris
1  Baudelaire  Charles        09/04/1821 Paris      31/08/1867 Paris
2     Rimbaud   Arthur  20/10/1854 Charleville  10/11/1891 Marseille

In [8]:
# pour les fichiers HTML, la fonction 'load' ne permet que de récupérer le code source
url = 'https://www.labri.fr/perso/schlick/outinfo/TEST/test-HTML.html'
page = load(url, split='') # on récupère sous forme de chaîne de caractères multi-lignes
print(page)

<html><head><meta charset="utf-8"/>
<style>
body {font-family:arial;}
table {border:2px solid black; border-spacing:0px; text-align:center;}
th,td {border:1px solid black;}
</style></head>
<body>
<h2>Auteurs français du XIXe siècle</h2>
<table cellpadding=5>
<tr>
<th>Nom <th>Prénom
<th>NaissanceDate <th>NaissanceLieu
<th>DécèsDate <th>DécèsLieu
<tr>
<td>Hugo <td>Victor
<td>26/02/1802 <td>Besançon
<td>22/05/1885 <td>Paris
<tr>
<td>Baudelaire <td>Charles
<td>09/04/1821 <td>Paris
<td>31/08/1867 <td>Paris
<tr>
<td>Rimbaud <td>Arthur
<td>20/10/1854 <td>Charleville
<td>10/11/1891 <td>Marseille
</table>
</body></html>

In [9]:
# la fonction 'pd.read_html' permet de récupérer toutes les tables à l'intérieur de la page
table = pd.read_html('https://www.labri.fr/perso/schlick/outinfo/TEST/test-HTML.html')
table[0] # on affiche la table d'index 0 (c'est la seule qui est présente dans le fichier)

          Nom   Prénom NaissanceDate NaissanceLieu   DécèsDate  DécèsLieu
0        Hugo   Victor    26/02/1802      Besançon  22/05/1885      Paris
1  Baudelaire  Charles    09/04/1821         Paris  31/08/1867      Paris
2     Rimbaud   Arthur    20/10/1854   Charleville  10/11/1891  Marseille

In [10]:
# ATTENTION : la fonction 'pd.read_html' peut être bloquée par les filtres anti-scraping
url = 'https://www.transfermarkt.fr/vereins-statistik/wertvollstemannschaften/marktwertetop'
#page = pd.read_html(url) # HTTP error 403 : forbidden (= accès interdit hors navigateur)

In [11]:
# la fonction 'fetch' du module 'tools' permet de contourner ce filtre anti-scraping
# en faisant croire au site web, que c'est un navigateur qui est connecté et non pas un robot
page = pd.read_html(fetch(url)) # il suffit de filtrer l'URL avec 'fetch'
page[1] # on affiche la table d'index 1 (c'est celle-là qui nous intéresse sur la page)

     #  Unnamed: 1                    Club     Compétition Valeur marchande
0    1         NaN             Real Madrid          LaLiga      1,36 mrd. €
1    2         NaN         Manchester City  Premier League      1,26 mrd. €
2    3         NaN              Arsenal FC  Premier League      1,17 mrd. €
3    4         NaN              Chelsea FC  Premier League    963,20 mio. €
4    5         NaN            FC Barcelone          LaLiga    946,00 mio. €
5    6         NaN           Bayern Munich      Bundesliga    936,70 mio. €
6    7         NaN            FC Liverpool  Premier League    931,00 mio. €
7    8         NaN     Paris Saint-Germain         Ligue 1    892,50 mio. €
8    9         NaN       Manchester United  Premier League    854,15 mio. €
9   10         NaN       Tottenham Hotspur  Premier League    788,30 mio. €
10  11         NaN             Inter Milan         Serie A    677,30 mio. €
11  12         NaN        Newcastle United  Premier League    657,65 mio. €
12  13         NaN     Bayer 04 Leverkusen      Bundesliga    635,10 mio. €
13  14         NaN             Aston Villa  Premier League    615,45 mio. €
14  15         NaN          Juventus Turin         Serie A    594,20 mio. €
15  16         NaN  Brighton & Hove Albion  Premier League    574,60 mio. €
16  17         NaN                AC Milan         Serie A    562,00 mio. €
17  18         NaN              RB Leipzig      Bundesliga    517,90 mio. €
18  19         NaN      Atlético de Madrid          LaLiga    511,00 mio. €
19  20         NaN         West Ham United  Premier League    481,50 mio. €
20  21         NaN       Borussia Dortmund      Bundesliga    474,90 mio. €
21  22         NaN             Atalanta BC         Serie A    447,60 mio. €
22  23         NaN           Real Sociedad          LaLiga    443,70 mio. €
23  24         NaN             Sporting CP   Liga Portugal    443,50 mio. €
24  25         NaN          Crystal Palace  Premier League    438,00 mio. €

<h2 style="padding:16px; color:#FFF; background:#07D">B - requests</h2>

Lorsque l'interaction avec le serveur web nécessite plus de paramètres que la simple lecture d'une page web, l'association **`load + fetch + pandas`** ne suffit pas toujours. Dans ces cas, des outils plus évolués, tels que la bibliothèque **`requests`** permettent d'effecteur des requêtes HTTP plus complexes. Le package **`requests`** ne fait pas partie de la bibliothèque standard de Python, elle nécessite donc une installation spécifique à l'aide de l'outil **`pip`**, mais comme les autres packages très populaires dans le domaine des Sciences des Données, elle est directement incluse dans la distribution **Anaconda**. Comme d'habitude, la documentation complète du package se trouve sur le site [**ReadTheDocs**](https://requests.readthedocs.io/en/latest)

La plus-value principale de **requests** est la possibilité de gérer de manière fine les deux types de commandes impliquées dans le protocole HTTP : la commande **POST** pour envoyer des informations et la commande **GET** pour récupérer des informations. Voici quelques exemples d'utilisation :

---
### 1 - Utilisation des requêtes GET

In [12]:
import requests # import du package 'requests'

# on définit une fonction url_get pour regrouper la séquence des opérations habituelles d'une requête GET
def url_get(url, **args):
  """apply GET request on provided URL, using optional arguments stored in dictionary 'args'"""
  headers = {'User-Agent':'Mozilla/5.0'} # use Mozilla/Firefox user agent (anti-scraping filter)
  page = requests.get(url, headers=headers, params=args) # connect to provided URL and get page
  page.raise_for_status() # raise HTTPError exception when connection or server error
  return page # return page when status is OK

In [13]:
# le site 'catfact.ninja' est un générateur de données JSON à la volée
# à chaque fois que vous exécutez la cellule, les données renvoyées sont différentes
url = 'https://catfact.ninja/fact'

page = load(url, split='') # on récupère le contenu sous forme de chaîne multi-lignes
print(page, '\n')
fact = eval(page,{},{})['fact'] # on convertit en dictionnaire et on récupère la valeur associée à 'fact'
print(fact)

{"fact":"Approximately 24 cat skins can make a coat.","length":43}

Approximately 24 cat skins can make a coat.

In [14]:
# avec la fonction 'url_get' le processus va être plus simple

page = url_get(url) # on récupère la réponse du site sous forme d'un objet 'Request'
print(page.text, '\n') # que l'on peut convertir en chaîne multi-lignes
print(page.json()['fact']) # ou en JSON pour lequel on peut extraire la valeur associée à 'fact'

{"fact":"Normal body temperature for a cat is 102 degrees F.","length":51}

Normal body temperature for a cat is 102 degrees F.

In [15]:
# mais surtout, la fonction 'url_get' permet de transmettre des paramètres à la requête GET

url = 'https://catfact.ninja/facts' # cette page va renvoyer plusieurs phrases dans le JSON
page = url_get(url, limit=5) # on transmet limit=5 à la requête
print(page.text, '\n') # on affiche la réponse obtenue sous forme de chaîne de caractères

facts = [f"● {fact['fact']}" for fact in page.json()['data']] # on extrait chaque valeur associée à 'fact'
print('\n'.join(facts)) # et on affiche la liste obtenue comme une chaîne multi-ligne

{"current_page":1,"data":[{"fact":"Unlike dogs, cats do not have a sweet tooth. Scientists believe this is due to a mutation in a key taste receptor.","length":114},{"fact":"When a cat chases its prey, it keeps its head level. Dogs and humans bob their heads up and down.","length":97},{"fact":"The technical term for a cat\u2019s hairball is a \u201cbezoar.\u201d","length":54},{"fact":"A group of cats is called a \u201cclowder.\u201d","length":38},{"fact":"A cat can\u2019t climb head first down a tree because every claw on a cat\u2019s paw points the same way. To get down from a tree, a cat must back down.","length":142}],"first_page_url":"https:\/\/catfact.ninja\/facts?page=1","from":1,"last_page":67,"last_page_url":"https:\/\/catfact.ninja\/facts?page=67","links":[{"url":null,"label":"Previous","active":false},{"url":"https:\/\/catfact.ninja\/facts?page=1","label":"1","active":true},{"url":"https:\/\/catfact.ninja\/facts?page=2","label":"2","active":false},{"url":"https:\/\/catfact.ninja\/facts?page=3","label":"3","active":false},{"url":"https:\/\/catfact.ninja\/facts?page=4","label":"4","active":false},{"url":"https:\/\/catfact.ninja\/facts?page=5","label":"5","active":false},{"url":"https:\/\/catfact.ninja\/facts?page=6","label":"6","active":false},{"url":"https:\/\/catfact.ninja\/facts?page=7","label":"7","active":false},{"url":"https:\/\/catfact.ninja\/facts?page=8","label":"8","active":false},{"url":"https:\/\/catfact.ninja\/facts?page=9","label":"9","active":false},{"url":"https:\/\/catfact.ninja\/facts?page=10","label":"10","active":false},{"url":null,"label":"...","active":false},{"url":"https:\/\/catfact.ninja\/facts?page=66","label":"66","active":false},{"url":"https:\/\/catfact.ninja\/facts?page=67","label":"67","active":false},{"url":"https:\/\/catfact.ninja\/facts?page=2","label":"Next","active":false}],"next_page_url":"https:\/\/catfact.ninja\/facts?page=2","path":"https:\/\/catfact.ninja\/facts","per_page":5,"prev_page_url":null,"to":5,"total":332}

● Unlike dogs, cats do not have a sweet tooth. Scientists believe this is due to a mutation in a key taste receptor.
● When a cat chases its prey, it keeps its head level. Dogs and humans bob their heads up and down.
● The technical term for a cat’s hairball is a “bezoar.”
● A group of cats is called a “clowder.”
● A cat can’t climb head first down a tree because every claw on a cat’s paw points the same way. To get down from a tree, a cat must back down.

In [16]:
# encore mieux : on définit un fonction 'translate' basée sur une connexion au site 'mymemory'
def translate(text, pair='en|fr'):
  url = 'https://api.mymemory.translated.net/get' # set URL for translation website
  page = url_get(url, q=text, langpair=pair) # set parameters for translation
  #print(page.text, '\n') # on affiche la réponse obtenue sous forme de chaîne de caractères
  return page.json()['responseData']['translatedText'] # extract translated text

In [17]:
print(translate(fact))

Environ 24 peaux de chat peuvent faire un manteau.

In [18]:
print('\n'.join(map(translate,facts))) # on applique la fonction 'translate' à chaque élément de 'facts'

● Contrairement aux chiens, les chats n'ont pas la dent sucrée. Les scientifiques pensent que cela est dû à une mutation d'un récepteur gustatif clé.
● Lorsqu'un chat poursuit sa proie, il garde la tête à niveau. Les chiens et les humains hochent la tête de haut en bas.
● Le terme technique pour la boule de poils d'un chat est un « bézoar ».
● Un groupe de chats est appelé « clowder ».
● Un chat ne peut pas descendre la tête la première d'un arbre parce que chaque griffe sur la patte d'un chat pointe de la même manière. Pour descendre d'un arbre, un chat doit reculer.

---
### 2 - Utilisation des requêtes POST

In [19]:
# on définit une fonction url_post pour regrouper la séquence des opérations habituelles d'une requête POST
def url_post(url, data):
  """apply POST request on provided URL, using optional arguments stored in dictionary 'args'"""
  headers = {'User-Agent':'Mozilla/5.0'} # use Mozilla/Firefox user agent (anti-scraping filter)
  page = requests.post(url, headers=headers, data=data) # connect to provided URL and get page
  page.raise_for_status() # raise HTTPError exception when connection or server error
  return page # return page when status is OK

In [20]:
url = 'https://reqres.in/api/login' # URL hébergeant un service de test de connexions avec identification
credentials = dict(email='eve.holt@reqres.in', password='cityslicka') # paramètres de connexion
data = url_post(url, credentials) # on envoie les paramètres à la requête POST
print(data.json()) # on convertit la réponse au format JSON

{'token': 'QpwL5tke4Pnpja7X4'}

In [21]:
url = 'https://httpbin.org/post' # URL hébergeant un service de test pour les requêtes POST
message = dict(name='toto', message='Hello')
data = url_post(url, message) # on envoie les paramètres à la requête POST
print(data.json()) # on convertit la réponse au format JSON

{'args': {}, 'data': '', 'files': {}, 'form': {'message': 'Hello', 'name': 'toto'}, 'headers': {'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '23', 'Content-Type': 'application/x-www-form-urlencoded', 'Host': 'httpbin.org', 'User-Agent': 'Mozilla/5.0', 'X-Amzn-Trace-Id': 'Root=1-674da1e1-0d4661df37c5e26d6b32b708'}, 'json': None, 'origin': '147.210.129.68', 'url': 'https://httpbin.org/post'}

<h2 style="padding:16px; color:#FFF; background:#07D">B - Beautiful Soup</h2>

Lorsque les données à récupérer dans une page HTML sont regroupées dans une balise **`<table>`**, la fonction **`read_html`** de **pandas** est parfaitement adaptée. Parfois, il faut effectuer quelques manipulations en post-traitement pour supprimer ou réorganiser certaines colonnes, mais cela ne nécessite habituellement pas plus de 2 ou 3 lignes de code. Par contre, lorsque les données ne sont pas structurées sous forme de tables HTML, mais en utilisant des combinaisons de balises **`<div>`** et **`<span>`**, il faudra utiliser des packages spécifiquement développés pour effectuer un ***web scraping*** finement paramétrable. De même, lorsque les données sont réparties sur de nombreuses pages au sein d'un même site, il faudra mettre en oeuvre des outils automatiques pour réaliser le ***wen crawling*** afin de ne pas devoir récupérer les données manuellement, page par page.

Il existe trois principales bibliothèques en Python pour effectuer ce type de tâches : [**BeautifulSoup**](https://beautiful-soup-4.readthedocs.io/en/latest), [**Scrapy**](https://docs.scrapy.org/en/latest) et [**Selenium**](https://selenium-python.readthedocs.io) par desd'une sont **`Beautiful Soup`** est une bibliothèque Python qui permet de manipuler très efficacement des données HTML et XML. Dans ce cours, nous allons simplement explorer quelques fonctionnalités de **BeautifulSoup** qui est le plus simple à mettre en oeuvre parmi ces trois packages. Pour certaines extractions de données avancées, vous serez peut-être amenés à utiliser les deux autres, c'est pour cela que j'ai mis, ci-dessus, les liens vers la documentation sur le site **ReadTheDocs**.

Le package **`BeautifulSoup`** ne fait pas partie de la bibliothèque standard de Python, elle nécessite donc une installation spécifique à l'aide de l'outil **`pip`**, mais comme le package **`requests`**, va très grande popularité dans le domaine des Sciences des Données, fait qu'elle est directement incluse dans la distribution **Anaconda**. Il faut noter qu'à l'inverse **Scrapy** et **Selenium** ne sont pas incluses par défaut dans **Anaconda**, du fait de leur utilisation plus spécialisée.

In [22]:
from bs4 import BeautifulSoup as bs # import de la fonction 'BeautifulSoup' du package bs4'

In [23]:
# le site 'quotes.toscrape.com' est un site d'entraînement au scraping
page = load('https://quotes.toscrape.com', split='') # on récupère la page HTML en mode texte
print(page[800:1150]) # on affiche un extrait de la page pour voir la structure du HTML

       <span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>
        <span>by <small class="author" itemprop="author">Albert Einstein</small>
        <a href="/author/Albert-Einstein">(about)</a>
        </span>
        <div class="tags">

In [24]:
soup = bs(page, 'html.parser') # on active le 'parsing' du contenu HTML avec la fonction 'bs'
print(str(soup)[565:880]) # les lignes ont été 'stripées' donc il faut ajuster la position de l'extrait

<span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>
<span>by <small class="author" itemprop="author">Albert Einstein</small>
<a href="/author/Albert-Einstein">(about)</a>
</span>
<div class="tags">

In [25]:
for quote in soup.find_all('div', class_='quote'): # on parcourt toutes les balises <div class='quote'>
  text = quote.find('span', class_='text').text # on récupère la balise <span class='text'>...</span>
  author = quote.find('small', class_='author').text # idem pour <small class='author'>...</small>
  print(f"● {text} ({author})") # on affiche la citation trouvée
  #print(f"● {translate(text)} ({author})\n") # on traduit la citation en français

● “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.” (Albert Einstein)
● “It is our choices, Harry, that show what we truly are, far more than our abilities.” (J.K. Rowling)
● “There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.” (Albert Einstein)
● “The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.” (Jane Austen)
● “Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.” (Marilyn Monroe)
● “Try not to become a man of success. Rather become a man of value.” (Albert Einstein)
● “It is better to be hated for what you are than to be loved for what you are not.” (André Gide)
● “I have not failed. I've just found 10,000 ways that won't work.” (Thomas A. Edison)
● “A woman is like a tea bag; you never know how strong it is until it's in hot water.” (Eleanor Roosevelt)
● “A day without sunshine is like, you know, night.” (Steve Martin)

In [26]:
base = url = 'https://quotes.toscrape.com/' # on stocke à part l'URL de départ
while url: # on itère tant qu'il reste des pages
  page = load(url, split='') # on récupère la page HTML en mode texte
  soup = bs(page, 'html.parser') # on active le 'parsing' du contenu HTML
  for quote in soup.find_all('div', class_='quote'): # on parcourt toutes les balises <div class='quote'>
    text = quote.find('span', class_='text').text # on récupère la balise <span class='text'>...</span>
    author = quote.find('small', class_='author').text # idem pour <small class='author'>...</small>
    print(f"● {text} ({author})") # on affiche la citation trouvée
    newpage = soup.find('li', class_='next') # on cherche le lien vers la page suivante
    url = base + newpage.find('a')['href'] if newpage else '' # on met à jour l'URL

● “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.” (Albert Einstein)
● “It is our choices, Harry, that show what we truly are, far more than our abilities.” (J.K. Rowling)
● “There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.” (Albert Einstein)
● “The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.” (Jane Austen)
● “Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.” (Marilyn Monroe)
● “Try not to become a man of success. Rather become a man of value.” (Albert Einstein)
● “It is better to be hated for what you are than to be loved for what you are not.” (André Gide)
● “I have not failed. I've just found 10,000 ways that won't work.” (Thomas A. Edison)
● “A woman is like a tea bag; you never know how strong it is until it's in hot water.” (Eleanor Roosevelt)
● “A day without sunshine is like, you know, night.” (Steve Martin)
● “This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about.” (Marilyn Monroe)
● “It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.” (J.K. Rowling)
● “If you can't explain it to a six year old, you don't understand it yourself.” (Albert Einstein)
● “You may not be her first, her last, or her only. She loved before she may love again. But if she loves you now, what else matters? She's not perfect—you aren't either, and the two of you may never be perfect together but if she can make you laugh, cause you to think twice, and admit to being human and making mistakes, hold onto her and give her the most you can. She may not be thinking about you every second of the day, but she will give you a part of her that she knows you can break—her heart. So don't hurt her, don't change her, don't analyze and don't expect more than she can give. Smile when she makes you happy, let her know when she makes you mad, and miss her when she's not there.” (Bob Marley)
● “I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living.” (Dr. Seuss)
● “I may not have gone where I intended to go, but I think I have ended up where I needed to be.” (Douglas Adams)
● “The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference.” (Elie Wiesel)
● “It is not a lack of love, but a lack of friendship that makes unhappy marriages.” (Friedrich Nietzsche)
● “Good friends, good books, and a sleepy conscience: this is the ideal life.” (Mark Twain)
● “Life is what happens to us while we are making other plans.” (Allen Saunders)
● “I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know any other way of loving but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close.” (Pablo Neruda)
● “For every minute you are angry you lose sixty seconds of happiness.” (Ralph Waldo Emerson)
● “If you judge people, you have no time to love them.” (Mother Teresa)
● “Anyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car.” (Garrison Keillor)
● “Beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye.” (Jim Henson)
● “Today you are You, that is truer than true. There is no one alive who is Youer than You.” (Dr. Seuss)
● “If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales.” (Albert Einstein)
● “It is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all - in which case, you fail by default.” (J.K. Rowling)
● “Logic will get you from A to Z; imagination will get you everywhere.” (Albert Einstein)
● “One good thing about music, when it hits you, you feel no pain.” (Bob Marley)
● “The more that you read, the more things you will know. The more that you learn, the more places you'll go.” (Dr. Seuss)
● “Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?” (J.K. Rowling)
● “The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.” (Bob Marley)
● “Not all of us can do great things. But we can do small things with great love.” (Mother Teresa)
● “To the well-organized mind, death is but the next great adventure.” (J.K. Rowling)
● “All you need is love. But a little chocolate now and then doesn't hurt.” (Charles M. Schulz)
● “We read to know we're not alone.” (William Nicholson)
● “Any fool can know. The point is to understand.” (Albert Einstein)
● “I have always imagined that Paradise will be a kind of library.” (Jorge Luis Borges)
● “It is never too late to be what you might have been.” (George Eliot)
● “A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one.” (George R.R. Martin)
● “You can never get a cup of tea large enough or a book long enough to suit me.” (C.S. Lewis)
● “You believe lies so you eventually learn to trust no one but yourself.” (Marilyn Monroe)
● “If you can make a woman laugh, you can make her do anything.” (Marilyn Monroe)
● “Life is like riding a bicycle. To keep your balance, you must keep moving.” (Albert Einstein)
● “The real lover is the man who can thrill you by kissing your forehead or smiling into your eyes or just staring into space.” (Marilyn Monroe)
● “A wise girl kisses but doesn't love, listens but doesn't believe, and leaves before she is left.” (Marilyn Monroe)
● “Only in the darkness can you see the stars.” (Martin Luther King Jr.)
● “It matters not what someone is born, but what they grow to be.” (J.K. Rowling)
● “Love does not begin and end the way we seem to think it does. Love is a battle, love is a war; love is a growing up.” (James Baldwin)
● “There is nothing I would not do for those who are really my friends. I have no notion of loving people by halves, it is not my nature.” (Jane Austen)
● “Do one thing every day that scares you.” (Eleanor Roosevelt)
● “I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.” (Marilyn Monroe)
● “If I were not a physicist, I would probably be a musician. I often think in music. I live my daydreams in music. I see my life in terms of music.” (Albert Einstein)
● “If you only read the books that everyone else is reading, you can only think what everyone else is thinking.” (Haruki Murakami)
● “The difference between genius and stupidity is: genius has its limits.” (Alexandre Dumas fils)
● “He's like a drug for you, Bella.” (Stephenie Meyer)
● “There is no friend as loyal as a book.” (Ernest Hemingway)
● “When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.” (Helen Keller)
● “Life isn't about finding yourself. Life is about creating yourself.” (George Bernard Shaw)
● “That's the problem with drinking, I thought, as I poured myself a drink. If something bad happens you drink in an attempt to forget; if something good happens you drink in order to celebrate; and if nothing happens you drink to make something happen.” (Charles Bukowski)
● “You don’t forget the face of the person who was your last hope.” (Suzanne Collins)
● “Remember, we're madly in love, so it's all right to kiss me anytime you feel like it.” (Suzanne Collins)
● “To love at all is to be vulnerable. Love anything and your heart will be wrung and possibly broken. If you want to make sure of keeping it intact you must give it to no one, not even an animal. Wrap it carefully round with hobbies and little luxuries; avoid all entanglements. Lock it up safe in the casket or coffin of your selfishness. But in that casket, safe, dark, motionless, airless, it will change. It will not be broken; it will become unbreakable, impenetrable, irredeemable. To love is to be vulnerable.” (C.S. Lewis)
● “Not all those who wander are lost.” (J.R.R. Tolkien)
● “Do not pity the dead, Harry. Pity the living, and, above all those who live without love.” (J.K. Rowling)
● “There is nothing to writing. All you do is sit down at a typewriter and bleed.” (Ernest Hemingway)
● “Finish each day and be done with it. You have done what you could. Some blunders and absurdities no doubt crept in; forget them as soon as you can. Tomorrow is a new day. You shall begin it serenely and with too high a spirit to be encumbered with your old nonsense.” (Ralph Waldo Emerson)
● “I have never let my schooling interfere with my education.” (Mark Twain)
● “I have heard there are troubles of more than one kind. Some come from ahead and some come from behind. But I've bought a big bat. I'm all ready you see. Now my troubles are going to have troubles with me!” (Dr. Seuss)
● “If I had a flower for every time I thought of you...I could walk through my garden forever.” (Alfred Tennyson)
● “Some people never go crazy. What truly horrible lives they must lead.” (Charles Bukowski)
● “The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.” (Terry Pratchett)
● “Think left and think right and think low and think high. Oh, the thinks you can think up if only you try!” (Dr. Seuss)
● “What really knocks me out is a book that, when you're all done reading it, you wish the author that wrote it was a terrific friend of yours and you could call him up on the phone whenever you felt like it. That doesn't happen much, though.” (J.D. Salinger)
● “The reason I talk to myself is because I’m the only one whose answers I accept.” (George Carlin)
● “You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one.” (John Lennon)
● “I am free of all prejudice. I hate everyone equally. ” (W.C. Fields)
● “The question isn't who is going to let me; it's who is going to stop me.” (Ayn Rand)
● “′Classic′ - a book which people praise and don't read.” (Mark Twain)
● “Anyone who has never made a mistake has never tried anything new.” (Albert Einstein)
● “A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.” (Jane Austen)
● “Remember, if the time should come when you have to make a choice between what is right and what is easy, remember what happened to a boy who was good, and kind, and brave, because he strayed across the path of Lord Voldemort. Remember Cedric Diggory.” (J.K. Rowling)
● “I declare after all there is no enjoyment like reading! How much sooner one tires of any thing than of a book! -- When I have a house of my own, I shall be miserable if I have not an excellent library.” (Jane Austen)
● “There are few people whom I really love, and still fewer of whom I think well. The more I see of the world, the more am I dissatisfied with it; and every day confirms my belief of the inconsistency of all human characters, and of the little dependence that can be placed on the appearance of merit or sense.” (Jane Austen)
● “Some day you will be old enough to start reading fairy tales again.” (C.S. Lewis)
● “We are not necessarily doubting that God will do the best for us; we are wondering how painful the best will turn out to be.” (C.S. Lewis)
● “The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.” (Mark Twain)
● “A lie can travel half way around the world while the truth is putting on its shoes.” (Mark Twain)
● “I believe in Christianity as I believe that the sun has risen: not only because I see it, but because by it I see everything else.” (C.S. Lewis)
● “The truth." Dumbledore sighed. "It is a beautiful and terrible thing, and should therefore be treated with great caution.” (J.K. Rowling)
● “I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.” (Jimi Hendrix)
● “To die will be an awfully big adventure.” (J.M. Barrie)
● “It takes courage to grow up and become who you really are.” (E.E. Cummings)
● “But better to get hurt by the truth than comforted with a lie.” (Khaled Hosseini)
● “You never really understand a person until you consider things from his point of view... Until you climb inside of his skin and walk around in it.” (Harper Lee)
● “You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children.” (Madeleine L'Engle)
● “Never tell the truth to people who are not worthy of it.” (Mark Twain)
● “A person's a person, no matter how small.” (Dr. Seuss)
● “... a mind needs books as a sword needs a whetstone, if it is to keep its edge.” (George R.R. Martin)

<h2 style="padding:0 0 8px; margin:0 -20px; color:#FFF; background:#07D; text-align:right">● ● ●</h3>